(()=>{
'use strict';
const C=window.AlphabetCoreV2;if(!C)throw new Error('AlphabetCoreV2 fehlt');
const STORAGE='uk-alpha-lab-v2',LEGACY='uk-alpha-lab-v1';
const app=document.getElementById('app');
let S=load(),screen='home',session=null,selectedLetter='',selectedPair=null,toastTimer=null,questionStarted=0,memoryTimer=null;

function load(){let raw=null;try{raw=JSON.parse(localStorage.getItem(STORAGE)||'null')}catch(_){raw=null}if(!raw){try{raw=JSON.parse(localStorage.getItem(LEGACY)||'null')}catch(_){raw=null}}const s=C.migrate(raw);persist(s);return s}
function persist(state=S){localStorage.setItem(STORAGE,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
function fmtMs(ms){return ms?`${(ms/1000).toFixed(ms<1000?2:1)} s`:'—'}
function fmtDate(ts){if(!ts)return '—';try{return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}catch(_){return '—'}}
function topbar(){return `<div class="topbar"><button class="brand-link" data-nav="home">🇺🇦 Alphabet Lab</button><div class="spacer"></div><div class="pill">🔥 ${S.streak}</div><div class="pill">XP ${S.xp}</div></div>`}
function nav(){return `<nav class="bottom-nav" aria-label="Hauptnavigation"><button data-nav="home">Start</button><button data-nav="examMenu">Prüfen</button><button data-nav="alphabet">Alphabet</button><button data-nav="stats">Statistik</button></nav>`}
function shell(inner,{navVisible=true}={}){app.innerHTML=topbar()+inner+(navVisible?nav():'');wireNav()}
function wireNav(){app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{clearTimeout(memoryTimer);screen=b.dataset.nav;session=null;render()})}
function toast(msg){let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.append(e)}e.textContent=msg;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,2200)}
function modal(icon,title,text,buttons=[['Weiter',()=>{}]]){const wrap=document.createElement('div');wrap.className='modal';wrap.innerHTML=`<section class="card modal-card"><div class="badge">${icon}</div><h2>${esc(title)}</h2><p class="muted">${esc(text)}</p><div class="actions" id="modalActions"></div></section>`;document.body.append(wrap);const a=wrap.querySelector('#modalActions');buttons.forEach(([label,fn,cls='primary'])=>{const b=document.createElement('button');b.className=`btn ${cls}`;b.textContent=label;b.onclick=()=>{wrap.remove();fn?.()};a.append(b)})}
function render(){clearTimeout(memoryTimer);if(screen==='home')renderHome();else if(screen==='examMenu')renderExamMenu();else if(screen==='exam')renderExam();else if(screen==='results')renderResults();else if(screen==='alphabet')renderAlphabet();else if(screen==='detail')renderDetail();else if(screen==='stats')renderStats();else if(screen==='errors')renderErrors();else if(screen==='battle')renderBattleLanding();else if(screen==='mastery')renderMastery();else if(screen==='science')renderScience();else if(screen==='write')renderWrite();}

function masteryBar(c){const m=C.letterMastery(S,c);return `<div class="mini-meter"><i style="width:${m}%"></i></div>`}
function statusClass(s){return s==='Sicher'?'good':s==='Unsicher'?'warn':s==='Problem'?'bad':'muted'}
function renderHome(){const st=C.statsToday(S),master=C.mastered(S),conf=C.topConfusions(S,5),weak=C.weakLetters(S,5);const allMastery=Math.round(C.ALPHABET.reduce((a,c)=>a+C.letterMastery(S,c),0)/33);
 shell(`${!S.diagnostic?`<section class="card diagnostic-callout"><div><div class="eyebrow">Erster Start</div><h2>50-Fragen-Startdiagnose</h2><p>Teste sofort, was schon sitzt. Keine Theorie davor, keine Lösungen während des Tests.</p></div><button class="btn primary" id="startDiagnostic">STARTDIAGNOSE</button></section>`:''}<section class="card hero exam-hero"><div class="eyebrow">Nur ukrainisches Alphabet</div><h1>Prüfen. Fehler sehen. Wiederholen.</h1><p>Du darfst sofort Prüfungen machen – auch wenn du fast nichts weißt. Deine Fehler werden dauerhaft gespeichert und automatisch zu neuem Lernstoff.</p><div class="actions"><button class="btn primary xl" id="bigStart">PRÜFUNG STARTEN</button><button class="btn" data-nav="examMenu">Prüfungsarten</button></div></section>
 <div class="grid stats-grid"><section class="card stat"><strong>${st.questions}</strong><span>Fragen heute</span></section><section class="card stat"><strong>${st.accuracy}%</strong><span>richtig heute</span></section><section class="card stat"><strong>${fmtMs(st.avgMs)}</strong><span>Ø Antwortzeit</span></section><section class="card stat"><strong>${master.readyCount}/33</strong><span>wirklich sicher</span></section></div>
 <section class="card"><div class="section-title"><h2>Alphabet Mastery</h2><small>${allMastery}% · datenbasiert</small></div><div class="progress"><i style="width:${allMastery}%"></i></div><p class="muted">Der Wert sinkt wieder, wenn neue Fehler auftauchen. „Sicher“ verlangt mehrere Fragetypen, hohe Genauigkeit und zeitlich getrennte Abrufe.</p><div class="actions"><button class="btn" data-nav="mastery">Abschlussstatus</button><button class="btn" data-nav="alphabet">Alle 33 ansehen</button></div></section>
 <section class="split"><div class="card"><div class="section-title"><h2>Deine Schwächen</h2></div>${weak.map(c=>{const x=C.summaryForLetter(S,c);return `<button class="row-link" data-letter="${c}"><span class="row-letter">${c}${C.DATA[c].lower}</span><span><b>${x.mastery}%</b><small>${x.status}</small></span></button>`}).join('')}</div>
 <div class="card"><div class="section-title"><h2>Verwechslungen</h2></div>${conf.length?conf.map(([p,n])=>`<button class="row-link" data-pair="${esc(p)}"><span>${esc(p)}</span><b>${n}×</b></button>`).join(''):'<p class="muted">Noch keine Verwechslungsmuster gespeichert.</p>'}<div class="actions"><button class="btn" data-nav="errors">Meine Fehler</button></div></div></section>
 <section class="card"><div class="section-title"><h2>Schnell starten</h2><small>wie bei einer Führerschein-App</small></div><div class="mode-grid"><button class="mode-card" data-preset="quick"><b>10</b><span>Schnellprüfung</span></button><button class="mode-card" data-preset="standard"><b>30</b><span>Standardprüfung</span></button><button class="mode-card" data-preset="large"><b>50</b><span>Große Prüfung</span></button><button class="mode-card" data-preset="errors"><b>!</b><span>Nur Fehler</span></button></div></section>`);
 document.getElementById('bigStart').onclick=()=>{screen='examMenu';render()};document.getElementById('startDiagnostic')?.addEventListener('click',startDiagnostic);wirePresetButtons();wireLetterPair();}

function presetConfig(name){const map={quick:{size:10,scope:'standard',title:'Schnellprüfung'},standard:{size:30,scope:'standard',title:'Standardprüfung'},large:{size:50,scope:'standard',title:'Große Prüfung'},weak:{size:30,scope:'weak',title:'Schwächenprüfung'},errors:{size:30,scope:'errors',title:'Fehlerprüfung'},fake:{size:30,scope:'fake',title:'Fake-Friend-Prüfung'},speed:{size:30,scope:'speed',title:'Speed-Prüfung'},audio:{size:30,scope:'audio',title:'Audio-Prüfung'}};return map[name]||map.standard}
function renderExamMenu(){shell(`<section class="card hero"><div class="eyebrow">Prüfungssimulator</div><h1>Die Prüfung ist Teil des Lernens.</h1><p><strong>Lernprüfung:</strong> sofortige Korrektur und Fehler kommen später in anderer Form wieder. <strong>Realprüfung:</strong> keine Lösung bis zur Auswertung.</p></section><section class="exam-list">${[
 ['quick','Schnellprüfung','10 Fragen · gut für zwischendurch'],['standard','Standardprüfung','30 Fragen · adaptiver Mix'],['large','Große Prüfung','50 Fragen · breiter Check'],['weak','Schwächenprüfung','30 Fragen · aktuelle Wissenslücken'],['errors','Nur meine Fehler','30 Fragen · frühere Fehler priorisiert'],['fake','Fake Friends','30 Fragen · В Н Р С У Х + Kontraste'],['speed','Speed-Prüfung','30 Fragen · erst sinnvoll bei etwas Genauigkeit'],['audio','Audio-Prüfung','30 Fragen · echte ukrainische Referenzwörter']].map(([id,t,d])=>`<section class="card exam-row"><div><h3>${t}</h3><p>${d}</p></div><div class="exam-actions"><button class="btn primary" data-start="${id}:learning">Lernprüfung</button><button class="btn" data-start="${id}:real">Realprüfung</button></div></section>`).join('')}</section>`);
 app.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{const [p,f]=b.dataset.start.split(':');startExam(p,f)});}
function wirePresetButtons(){app.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>startExam(b.dataset.preset,'learning'))}
function startExam(preset='standard',feedback='learning',extra={}){const cfg=presetConfig(preset),exam=C.buildExam(S,{size:cfg.size,scope:cfg.scope,feedback});session={kind:'exam',preset,title:extra.title||cfg.title,scope:cfg.scope,feedback,tasks:exam.tasks,index:0,correct:0,answers:[],errors:[],startedAt:Date.now(),repairQueue:[],certification:extra.certification||'',battle:extra.battle||null};screen='exam';renderExam()}
function startCustomTasks(tasks,title,feedback='learning',extra={}){session={kind:'exam',preset:extra.preset||'custom',title,scope:extra.scope||'custom',feedback,tasks:[...tasks],index:0,correct:0,answers:[],errors:[],startedAt:Date.now(),repairQueue:[],certification:extra.certification||'',battle:extra.battle||null};screen='exam';renderExam()}
function currentTask(){return session?.tasks?.[session.index]}
function examProgress(){return session.tasks.length?Math.round(session.index/session.tasks.length*100):0}
function renderExam(){const t=currentTask();if(!t)return finishExam();questionStarted=performance.now();let body='';const opts=t.options||[];
 if(t.type==='visual'||t.type==='speed'){body=`<div class="big-letter">${t.display}</div><div class="prompt">${esc(t.prompt)}</div>${answerButtons(opts,'ans')}`}
 else if(t.type==='memory'){body=`<div id="memoryFlash" class="big-letter">${t.display}</div><div id="memoryQuestion" class="hidden"><div class="prompt">Welcher Laut gehörte zum Zeichen?</div>${answerButtons(opts,'ans')}</div><div class="micro">500 ms ansehen → aus dem Gedächtnis antworten</div>`}
 else if(t.type==='reverse'||t.type==='find'||t.type==='contrast'){body=`${t.display?`<div class="pair">${esc(t.display)}</div>`:''}<div class="prompt">${esc(t.prompt)}</div>${letterButtons(opts,'ans')}`}
 else if(t.type==='lowercase'||t.type==='uppercase'){body=`<div class="big-letter">${t.display}</div><div class="prompt">${esc(t.prompt)}</div>${letterButtons(opts,'ans')}`}
 else if(t.type==='trueFalse'){body=`<div class="big-letter">${t.letter}</div><div class="prompt">${esc(t.prompt)}</div>${answerButtons(opts,'ans')}`}
 else if(t.type==='audio'){body=`<div class="audio-orb">🔊</div><div class="prompt">${esc(t.prompt)}</div><p class="muted center">Das ist eine echte ukrainische Wortaufnahme. Wörter dienen hier nur als Laut-/Schriftträger, nicht als Vokabellektion.</p><div class="audio-row"><button class="btn primary" id="playAudio">Audio abspielen</button></div>${letterButtons(opts,'ans')}`}
 shell(`<section class="lesson"><div class="lesson-head"><button class="btn" id="exitExam">← Menü</button><div class="progress"><i style="width:${examProgress()}%"></i></div><span class="tag">${session.index+1}/${session.tasks.length}</span></div><section class="card stage exam-stage"><div class="eyebrow">${esc(session.title)} · ${session.feedback==='learning'?'Lernprüfung':'Realprüfung'} · ${kindLabel(t.type)}</div>${body}<div id="feedback" class="feedback"></div><div id="correction" class="correction hidden"></div></section></section>`,{navVisible:false});
 document.getElementById('exitExam').onclick=()=>modal('↩','Prüfung verlassen?','Die laufende Prüfung wird nicht gewertet.',[['Verlassen',()=>{session=null;screen='home';render()},'danger'],['Weiterlernen',()=>{},'primary']]);
 if(t.type==='audio'){const b=document.getElementById('playAudio');b.onclick=()=>playLetter(t.letter,b);setTimeout(()=>playLetter(t.letter,b),120)}
 if(t.type==='memory'){const flash=document.getElementById('memoryFlash'),q=document.getElementById('memoryQuestion');memoryTimer=setTimeout(()=>{flash.classList.add('hidden');q.classList.remove('hidden');questionStarted=performance.now()},500)}
 app.querySelectorAll('[data-ans]').forEach(b=>b.onclick=()=>submitExamAnswer(b.dataset.ans,b));}
function answerButtons(opts,key){return `<div class="answers">${opts.map(x=>`<button class="answer" data-${key}="${esc(x)}">${esc(x)}</button>`).join('')}</div>`}
function letterButtons(opts,key){return `<div class="answers letter-answers">${opts.map(x=>`<button class="answer" data-${key}="${esc(x)}"><span>${esc(x)}</span></button>`).join('')}</div>`}
function kindLabel(k){return ({visual:'Zeichen → Laut',reverse:'Laut → Zeichen',audio:'Audio → Zeichen',lowercase:'Groß → klein',uppercase:'Klein → groß',contrast:'Verwechslung',trueFalse:'Richtig/Falsch',memory:'500-ms-Gedächtnis',find:'Visuelles Finden',speed:'Speed Recognition'})[k]||k}
function submitExamAnswer(value,button){if(session.locked)return;session.locked=true;const t=currentTask(),ms=Math.max(1,Math.round(performance.now()-questionStarted)),good=value===t.correct;const confusedWith=resolveConfusedLetter(t,value);C.recordAnswer(S,{letter:t.letter,good,kind:t.type,selected:value,confusedWith,ms,source:session.preset});persist();if(good)session.correct++;else session.errors.push({letter:t.letter,type:t.type,selected:value,correct:t.correct,ms,note:C.DATA[t.letter].note});session.answers.push({letter:t.letter,type:t.type,selected:value,correct:t.correct,good,ms,repair:!!t.repair});
 if(!good&&session.feedback==='learning'&&!t.repair){const repair=C.repairTask(t,S);const insert=Math.min(session.tasks.length,session.index+3+Math.floor(Math.random()*4));session.tasks.splice(insert,0,repair)}
 if(session.feedback==='real'){setTimeout(nextQuestion,120);return}
 button.classList.add(good?'correct':'wrong');const fb=document.getElementById('feedback'),cor=document.getElementById('correction');fb.className=`feedback ${good?'good':'bad'}`;fb.textContent=good?`✓ Richtig · ${fmtMs(ms)}`:`✕ Falsch · ${fmtMs(ms)}`;cor.classList.remove('hidden');cor.innerHTML=good?`<strong>${t.letter} = ${esc(C.DATA[t.letter].sound)}</strong>`:`<div class="correction-grid"><span>Deine Antwort <b class="bad-text">${esc(value)}</b></span><span>Richtig <b class="good-text">${esc(t.correct)}</b></span></div><p><strong>${t.letter}</strong> = ${esc(C.DATA[t.letter].sound)}. ${esc(C.DATA[t.letter].note)}</p><button class="btn" id="feedbackAudio">🔊 Referenzwort anhören</button>`;if(!good)document.getElementById('feedbackAudio').onclick=e=>playLetter(t.letter,e.currentTarget);setTimeout(nextQuestion,good?600:1900)}
function resolveConfusedLetter(t,value){if(value===t.letter||value===t.correct)return '';if(C.ALPHABET.includes(value))return value;const bySound=C.ALPHABET.find(c=>C.DATA[c].sound===value);if(bySound)return bySound;const byLower=C.ALPHABET.find(c=>C.DATA[c].lower===value);return byLower||''}
function nextQuestion(){session.index++;session.locked=false;if(session.index>=session.tasks.length)finishExam();else renderExam()}
function finishExam(){const total=session.answers.length,correct=session.correct,accuracy=total?correct/total:0,date=C.todayFrom();const summary={date,at:Date.now(),title:session.title,preset:session.preset,scope:session.scope,feedback:session.feedback,total,correct,accuracy,avgMs:Math.round(session.answers.reduce((a,x)=>a+x.ms,0)/Math.max(1,total)),errors:session.errors.slice(0,80)};C.recordExam(S,summary);if(session.preset==='diagnostic')S.diagnostic={date,score:correct,total,accuracy,completedAt:Date.now()};if(session.certification)C.addMasteryCheck(S,session.certification,summary);persist();session.summary=summary;screen='results';renderResults()}
function renderResults(){const r=session.summary,errors=session.errors,top=aggregateErrors(errors);shell(`<section class="card hero results-hero"><div class="eyebrow">PRÜFUNGSERGEBNIS</div><div class="score-ring"><strong>${r.correct}/${r.total}</strong><span>${Math.round(r.accuracy*100)}%</span></div><h1>${r.accuracy>=.9?'Stark.':r.accuracy>=.7?'Auf gutem Weg.':'Fehler = Lernstoff.'}</h1><p>${session.feedback==='real'?'Jetzt siehst du die vollständige Auswertung.':'Falsche Antworten wurden bereits in deinen Lernplan zurückgespielt.'}</p></section><section class="card"><div class="result-grid"><div><span>Ø Zeit</span><b>${fmtMs(r.avgMs)}</b></div><div><span>Fehler</span><b>${errors.length}</b></div><div><span>Modus</span><b>${session.feedback==='learning'?'Lernen':'Real'}</b></div></div><div class="actions"><button class="btn primary" id="trainErrors" ${errors.length?'':'disabled'}>MEINE FEHLER TRAINIEREN</button><button class="btn" id="again">NEUE PRÜFUNG</button><button class="btn" data-nav="home">Startseite</button></div></section>
 <section class="card"><div class="section-title"><h2>Fehleranalyse</h2><small>${errors.length?`${top.length} Problemzeichen`:'fehlerfrei'}</small></div>${errors.length?top.map(x=>`<div class="error-row"><span class="row-letter">${x.letter}</span><div><b>${x.count} Fehler</b><small>${x.samples.map(s=>`${esc(s.selected)} → ${esc(s.correct)}`).slice(0,3).join(' · ')}</small></div><button class="btn small" data-letter="${x.letter}">Details</button></div>`).join(''):'<p class="good-text center">Keine Fehler in dieser Prüfung.</p>'}</section>`);
 document.getElementById('trainErrors').onclick=()=>startExam('errors','learning');document.getElementById('again').onclick=()=>{screen='examMenu';session=null;render()};wireLetterPair();}
function aggregateErrors(errors){const m={};errors.forEach(e=>{m[e.letter]=m[e.letter]||{letter:e.letter,count:0,samples:[]};m[e.letter].count++;m[e.letter].samples.push(e)});return Object.values(m).sort((a,b)=>b.count-a.count)}

function renderErrors(){const letters=C.errorLetters(S),conf=C.topConfusions(S,10);shell(`<section class="card hero"><div class="eyebrow">Persönliches Fehlergedächtnis</div><h1>Meine Fehler</h1><p>Nichts verschwindet nach einer falschen Antwort. Häufige, langsame und alte Fehler werden in Prüfungen höher gewichtet.</p><div class="actions"><button class="btn primary" id="errorExam">Fehlerprüfung starten</button></div></section><section class="card"><div class="section-title"><h2>Fehler nach Buchstabe</h2></div>${letters.length?letters.map(c=>{const x=C.summaryForLetter(S,c);return `<button class="row-link" data-letter="${c}"><span class="row-letter">${c}</span><span><b>${x.wrong}× falsch</b><small>${x.topConfusion?`meist mit ${esc(x.topConfusion)} · ${x.topConfusionCount}×`:x.status}</small></span><span>${x.mastery}%</span></button>`}).join(''):'<p class="muted">Noch keine Fehler gespeichert.</p>'}</section><section class="card"><div class="section-title"><h2>Confusion Matrix</h2></div>${conf.length?conf.map(([p,n])=>`<button class="row-link" data-pair="${esc(p)}"><span>${esc(p)}</span><b>${n}×</b></button>`).join(''):'<p class="muted">Noch keine Paar-Verwechslungen.</p>'}</section>`);document.getElementById('errorExam').onclick=()=>startExam('errors','learning');wireLetterPair()}
function wireLetterPair(){app.querySelectorAll('[data-letter]').forEach(b=>b.onclick=()=>{selectedLetter=b.dataset.letter;screen='detail';render()});app.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{selectedPair=b.dataset.pair.split(' ↔ ');screen='battle';render()})}

function renderAlphabet(){shell(`<section class="card hero"><div class="eyebrow">33 Zeichen</div><h1>Alphabet-Übersicht</h1><p>Keine Häkchen für „einmal gesehen“. Jeder Status stammt aus Genauigkeit, Tempo, Fragetypen, Retention und Fehlern.</p></section><section class="letters detailed">${C.ALPHABET.map(c=>{const x=C.summaryForLetter(S,c);return `<button class="letter-chip" data-letter="${c}"><b>${c}${C.DATA[c].lower}</b><span class="${statusClass(x.status)}">${x.status}</span><strong>${x.mastery}%</strong>${masteryBar(c)}</button>`}).join('')}</section>`);wireLetterPair()}
function renderDetail(){const c=selectedLetter||C.ALPHABET[0],x=C.summaryForLetter(S,c),d=C.DATA[c],m=S.letters[c];shell(`<section class="card hero detail-hero"><div class="eyebrow">Buchstabenprofil</div><div class="detail-letter">${c}<span>${d.lower}</span></div><h1>${esc(d.sound)}</h1><div class="ipa">${esc(d.ipa)}</div><p>${esc(d.note)}</p><div class="actions"><button class="btn" id="playDetail">🔊 ${esc(d.word)} anhören</button><button class="btn primary" id="trainLetter">${c} TRAINIEREN</button><button class="btn" id="writeLetter">${c} SCHREIBEN</button></div></section><div class="grid stats-grid"><section class="card stat"><strong>${x.mastery}%</strong><span>Mastery</span></section><section class="card stat"><strong>${x.accuracy}%</strong><span>Genauigkeit</span></section><section class="card stat"><strong>${fmtMs(x.avgMs)}</strong><span>Ø Reaktion</span></section><section class="card stat"><strong>${x.typeCoverage}/10</strong><span>Fragetypen</span></section></div><section class="card"><div class="detail-table"><div><span>Gesehen</span><b>${x.seen}×</b></div><div><span>Richtig</span><b>${x.correct}</b></div><div><span>Falsch</span><b>${x.wrong}</b></div><div><span>Serie</span><b>${x.correctStreak}</b></div><div><span>Erfolgreiche Lerntage</span><b>${x.successDays}</b></div><div><span>Letzter Fehler</span><b>${fmtDate(x.lastWrongAt)}</b></div><div><span>Häufigste Verwechslung</span><b>${esc(x.topConfusion||'—')} ${x.topConfusionCount?`(${x.topConfusionCount}×)`:''}</b></div><div><span>Nächste Wiederholung</span><b>${x.nextDue?fmtDate(x.nextDue):'sofort'}</b></div></div></section><section class="card"><div class="section-title"><h2>Leistung nach Fragetyp</h2></div><div class="type-grid">${Object.entries(x.types).map(([k,v])=>`<div><span>${kindLabel(k)}</span><b>${v}%</b></div>`).join('')}</div></section>`);document.getElementById('playDetail').onclick=e=>playLetter(c,e.currentTarget);document.getElementById('trainLetter').onclick=()=>startFocusedExam(c);document.getElementById('writeLetter').onclick=()=>{screen='write';render()}}
function startFocusedExam(c){const types=['visual','reverse','audio','lowercase','uppercase','contrast','trueFalse','memory','find','speed'];const tasks=[];for(let i=0;i<20;i++)tasks.push(forceLetter(null,c,types[i%types.length]));startCustomTasks(tasks,`${c} Intensivtraining`,'learning',{preset:'focused',scope:'focused'})}
function forceLetter(task,c,type){const d=C.DATA[c],conf=C.SOUND_GROUPS[c]||[];const opts=()=>C.shuffle(C.uniq([c,...conf,...C.ALPHABET.filter(x=>x!==c)]).slice(0,4));if(type==='visual'||type==='speed'||type==='memory')return {letter:c,type,prompt:'Welcher Laut gehört zu diesem Zeichen?',display:c,correct:d.sound,options:C.shuffle(C.uniq([d.sound,...opts().filter(x=>x!==c).map(x=>C.DATA[x].sound)]).slice(0,4))};if(type==='reverse'||type==='find')return {letter:c,type,prompt:type==='find'?`Wähle ${c}.`:`Welcher ukrainische Buchstabe entspricht „${d.sound}“?`,correct:c,options:opts()};if(type==='audio')return {letter:c,type,prompt:c==='Ь'?'Hör das Referenzwort. Welches Zeichen markiert die Weichheit am Ende?':`Hör das Referenzwort. Welches Zeichen gehört an Position ${(d.audioIndex??0)+1}?`,correct:c,options:opts(),audioWord:d.word};if(type==='lowercase')return {letter:c,type,prompt:'Welcher Kleinbuchstabe gehört dazu?',display:c,correct:d.lower,options:C.shuffle(C.uniq([d.lower,...opts().filter(x=>x!==c).map(x=>C.DATA[x].lower)]).slice(0,4))};if(type==='uppercase')return {letter:c,type,prompt:'Welcher Großbuchstabe gehört dazu?',display:d.lower,correct:c,options:opts()};if(type==='contrast'){const o=conf[0]||opts().find(x=>x!==c);return {letter:c,type,prompt:`Welches Zeichen steht für „${d.sound}“?`,display:`${c} · ${o}`,correct:c,options:C.shuffle([c,o])}}if(type==='trueFalse')return {letter:c,type,prompt:`Richtig oder falsch: ${c} = ${d.sound}`,correct:'Richtig',options:['Richtig','Falsch']};return forceLetter(null,c,'visual')}

function startDiagnostic(){const exam=C.buildDiagnostic(S,{size:50});startCustomTasks(exam.tasks,'Startdiagnose','real',{preset:'diagnostic',scope:'diagnostic'})}
function renderWrite(){const c=selectedLetter||C.ALPHABET[0];shell(`<section class="lesson"><div class="lesson-head"><button class="btn" id="writeBack">← Buchstabe</button><div class="spacer"></div><span class="tag">Handschrift</span></div><section class="card stage"><div class="eyebrow">Motorische Spur</div><div class="prompt">Schreibe ${c} mehrfach über die helle Vorlage. Die App prüft nur, ob du wirklich gezeichnet hast – sie erfindet keine Handschrift-Note.</div><div class="canvas-wrap"><canvas class="trace-canvas" id="writeCanvas" width="760" height="760"></canvas><div class="trace-actions"><button class="btn" id="clearCanvas">Neu</button><button class="btn primary" id="saveWriting">Geschrieben</button></div></div></section></section>`,{navVisible:false});document.getElementById('writeBack').onclick=()=>{screen='detail';render()};setupWriteCanvas(c)}
function setupWriteCanvas(c){const canvas=document.getElementById('writeCanvas'),ctx=canvas.getContext('2d');let drawing=false,last=null,ink=0;function guide(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 540px system-ui';ctx.fillStyle='#e5e7eb';ctx.fillText(c,380,390);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#111827';ctx.lineWidth=24;ink=0}guide();const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.onpointerdown=e=>{e.preventDefault();drawing=true;last=point(e);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(!drawing)return;e.preventDefault();const p=point(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ink+=Math.hypot(p.x-last.x,p.y-last.y);last=p};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;last=null};document.getElementById('clearCanvas').onclick=guide;document.getElementById('saveWriting').onclick=()=>{if(ink<700){toast('Bitte das Zeichen erst sichtbar mehrfach nachziehen.');return}C.recordWriting(S,c);persist();toast('Schreibübung gespeichert.');screen='detail';render()}}

function renderStats(){const t=C.statsToday(S),hist=S.examHistory.slice(0,12),weak=C.weakLetters(S,1)[0],strong=[...C.ALPHABET].sort((a,b)=>C.letterMastery(S,b)-C.letterMastery(S,a))[0],conf=C.topConfusions(S,1)[0];shell(`<section class="card hero"><div class="eyebrow">Statistik</div><h1>Messbar statt gefühlt.</h1><p>Antwortzeit zählt erst dann stärker, wenn Genauigkeit vorhanden ist. Ein langsames richtiges Ergebnis ist besser als ein schnelles Raten.</p></section><div class="grid stats-grid"><section class="card stat"><strong>${t.exams}</strong><span>Prüfungen heute</span></section><section class="card stat"><strong>${t.questions}</strong><span>Fragen heute</span></section><section class="card stat"><strong>${t.accuracy}%</strong><span>richtig heute</span></section><section class="card stat"><strong>${fmtMs(t.avgMs)}</strong><span>Ø Zeit heute</span></section></div><section class="card"><div class="detail-table"><div><span>Stärkstes Zeichen</span><b>${strong} · ${C.letterMastery(S,strong)}%</b></div><div><span>Schwächstes Zeichen</span><b>${weak} · ${C.letterMastery(S,weak)}%</b></div><div><span>Häufigste Verwechslung</span><b>${conf?`${esc(conf[0])} · ${conf[1]}×`:'—'}</b></div><div><span>Lerntage</span><b>${S.studyDays.length}</b></div></div></section><section class="card"><div class="section-title"><h2>Letzte Prüfungen</h2></div>${hist.length?hist.map(h=>`<div class="history-row"><div><b>${esc(h.title||h.preset)}</b><small>${esc(h.date)} · ${h.feedback==='real'?'Real':'Lernen'}</small></div><strong>${h.correct}/${h.total} · ${Math.round(h.accuracy*100)}%</strong></div>`).join(''):'<p class="muted">Noch keine Prüfungen.</p>'}</section>`)}

function renderBattleLanding(){const pair=selectedPair||C.topConfusions(S,1)[0]?.[0]?.split(' ↔ ')||['Ш','Щ'];selectedPair=pair;const [a,b]=pair;const aM=C.summaryForLetter(S,a),bM=C.summaryForLetter(S,b);shell(`<section class="card hero"><div class="eyebrow">Schwächen-Battle</div><h1>${a} VS ${b}</h1><p>20 schnelle Aufgaben wechseln zwischen Laut, Zeichen, Audio, Kontrast und Gedächtnis. Das Paar wird nicht fünfmal identisch hintereinander gefragt.</p><div class="battle-score"><div><b>${a}</b><span>${aM.mastery}% Mastery</span></div><div><b>${b}</b><span>${bM.mastery}% Mastery</span></div></div><div class="actions"><button class="btn primary" id="startBattle">BATTLE STARTEN</button></div></section>`);document.getElementById('startBattle').onclick=()=>{const tasks=[];const types=['contrast','visual','reverse','audio','memory','speed','trueFalse','find'];for(let i=0;i<20;i++){const c=i%2?a:b;tasks.push(forceLetter(null,c,types[i%types.length]))}startCustomTasks(tasks,`${a} VS ${b}`,'learning',{preset:'battle',scope:'battle',battle:pair})}}

function renderMastery(){const m=C.mastered(S),all=Math.round(C.ALPHABET.reduce((a,c)=>a+C.letterMastery(S,c),0)/33);shell(`<section class="card hero"><div class="eyebrow">Abschlusskriterien</div><h1>${m.done?'UKRAINISCHES ALPHABET GEMEISTERT':'Noch kein künstlicher Abschluss.'}</h1><p>Mastery bleibt dynamisch. Neue Fehler können einen zuvor sicheren Buchstaben wieder zurückstufen.</p></section><section class="card"><div class="section-title"><h2>Gesamt</h2><small>${m.readyCount}/33 sicher · Ø ${all}%</small></div><div class="progress"><i style="width:${Math.round(m.readyCount/33*100)}%"></i></div></section><section class="mastery-grid"><div class="mastery-item ${m.allLetters?'pass':''}"><strong>33/33 sicher</strong><small>hohe Genauigkeit, ≥5 Fragetypen, Retention, Schreiben</small></div><div class="mastery-item ${m.finals?'pass':''}"><strong>Abschlussprüfung</strong><small>≥95 % an zwei verschiedenen Tagen</small></div><div class="mastery-item ${m.fake?'pass':''}"><strong>Fake Friends</strong><small>100 % in einer 30er Prüfung</small></div><div class="mastery-item ${m.audio?'pass':''}"><strong>Audio</strong><small>≥95 % in einer 30er Prüfung</small></div><div class="mastery-item ${m.retention?'pass':''}"><strong>Langzeit</strong><small>mehrere Lerntage / verzögerter Abruf</small></div><div class="mastery-item ${m.speed?'pass':''}"><strong>Automatisierung</strong><small>Ø Erkennung ≤2,5 s · aktuell ${fmtMs(m.avgRecognitionMs)}</small></div></section><section class="card"><div class="section-title"><h2>Mastery-Prüfungen</h2></div><div class="mode-grid"><button class="mode-card" id="finalTest"><b>100</b><span>Abschlussprüfung</span></button><button class="mode-card" id="fakeTest"><b>30</b><span>Fake Friends</span></button><button class="mode-card" id="audioTest"><b>33</b><span>Audio</span></button><button class="mode-card" id="retTest"><b>50</b><span>Langzeitcheck</span></button></div></section>`);document.getElementById('finalTest').onclick=()=>startCertification('final',100,'standard','Abschlussprüfung');document.getElementById('fakeTest').onclick=()=>startCertification('fake',30,'fake','Fake-Friend-Mastery');document.getElementById('audioTest').onclick=()=>startCertification('audio',33,'audio','Audio-Mastery');document.getElementById('retTest').onclick=()=>startCertification('retention',50,'weak','Langzeitprüfung')}
function startCertification(type,size,scope,title){const exam=C.buildExam(S,{size,scope,feedback:'real'});startCustomTasks(exam.tasks,title,'real',{preset:`mastery-${type}`,scope,certification:type})}

function renderScience(){shell(`<section class="card hero"><div class="eyebrow">Produktphilosophie</div><h1>Prüfung → Fehler → Wiederholung.</h1><p>Die App ist bewusst näher an einer guten Führerschein-Lernapp als an einem klassischen Sprachkurs.</p></section><section class="card science"><ol><li><strong>Retrieval Practice:</strong> sehr früh testen, statt erst lange Theorie zu konsumieren.</li><li><strong>Spacing:</strong> Fehler kommen nach Minuten zurück, stabile Antworten später über Stunden und Tage.</li><li><strong>Interleaving:</strong> derselbe Buchstabe erscheint in unterschiedlichen Fragetypen, nicht nur als identische Karte.</li><li><strong>Fehlergedächtnis:</strong> falsche Antworten und konkrete Verwechslungen bleiben im Profil.</li><li><strong>Antwortzeit:</strong> langsames Richtig zählt weniger als automatisches Richtig, aber erst wenn Genauigkeit vorhanden ist.</li><li><strong>Handschrift:</strong> motorisches Schreiben ergänzt Erkennen und Hören; es wird nicht mit einer Fake-KI-Note bewertet.</li><li><strong>Keine Scheinsicherheit:</strong> Mastery braucht mehrere Tage, Fragetypen und wiederholte Abschlussprüfungen.</li></ol><p class="muted">Die Lernprinzipien sind forschungsbasiert; die konkrete App selbst ist damit nicht automatisch klinisch oder experimentell validiert.</p></section>`)}

function playLetter(c,button){const src=window.UKRAINIAN_PRONUNCIATION_AUDIO?.[c];if(src){const a=new Audio(src);if(button)button.disabled=true;const done=()=>{if(button)button.disabled=false};a.onended=done;a.onerror=()=>{done();ttsWord(c)};a.play().catch(()=>{done();ttsWord(c)});return}ttsWord(c)}
function ttsWord(c){if(!('speechSynthesis' in window))return;const u=new SpeechSynthesisUtterance(C.DATA[c].word);u.lang='uk-UA';u.rate=.72;speechSynthesis.cancel();speechSynthesis.speak(u)}

window.AlphabetLab={version:C.VERSION,state:()=>structuredClone(S),export:()=>JSON.stringify(S,null,2),reset(){if(confirm('Alphabet-Lernstand wirklich löschen?')){localStorage.removeItem(STORAGE);localStorage.removeItem(LEGACY);S=C.freshState();persist();screen='home';render()}},startExam};
render();
})();
