(function(root){
'use strict';

const VERSION=2;
const DAY=86400000, HOUR=3600000, MIN=60000;
const ALPHABET='А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я'.split(' ');
const LEARN_ORDER=['А','І','К','М','О','Т','Е','В','Н','Р','С','У','Х','Б','П','Д','Л','Ф','Г','Ґ','З','Ж','И','Ї','Й','Є','Ц','Ч','Ш','Щ','Ь','Ю','Я'];
const FAKE_FRIENDS=['В','Н','Р','С','У','Х'];
const HARD=new Set(['В','Г','Ґ','Е','Є','Ж','З','И','І','Ї','Й','Н','П','Р','С','У','Х','Ц','Ч','Ш','Щ','Ь','Ю','Я']);
const VOWELS=['А','Е','Є','И','І','Ї','О','У','Ю','Я'];
const SOUND_GROUPS={
  'Г':['Ґ','Х'],'Ґ':['Г','К'],'Е':['Є','И'],'Є':['Е','Ї'],'Ж':['Ш','Щ'],'З':['С','Ц'],'И':['І','Е','Ї'],'І':['И','Ї','Й'],'Ї':['І','Й','Є'],'Й':['Ї','І','И'],
  'Н':['П','И','К'],'П':['Н','Р','Б'],'Р':['П','В','Б'],'С':['З','Ц','Є'],'У':['В','И','Ч'],'Х':['Г','К','Ж'],'Ц':['Ч','С','З'],'Ч':['Ц','Ш','Щ'],
  'Ш':['Щ','Ж','Ч'],'Щ':['Ш','Ж','Ч'],'Ь':['Й','І','Ї'],'Ю':['У','Я','Є'],'Я':['Ю','Є','Ї'],'В':['Б','У','Н'],'Б':['В','П','Р'],
  'А':['О','Я','Д'],'Д':['Л','А','П'],'К':['Х','Н','Ж'],'Л':['Д','П','И'],'М':['Н','И','Ш'],'О':['А','С','Ю'],'Т':['Г','П','І'],'Ф':['О','Х','Р']
};
const DATA={
'А':{lower:'а',ipa:'/a/',sound:'A wie in „Auto“',short:'A',word:'автобус',de:'Bus',note:'Form und Laut sind vertraut.'},
'Б':{lower:'б',ipa:'/b/',sound:'B wie in „Ball“',short:'B',word:'бабуся',de:'Oma',note:'Б = B. Nicht mit В verwechseln.'},
'В':{lower:'в',ipa:'/ʋ ~ w/',sound:'ähnlich deutschem W',short:'W/V',word:'вода',de:'Wasser',note:'Sieht wie B aus, klingt aber ungefähr W/V.'},
'Г':{lower:'г',ipa:'/ɦ/',sound:'stimmhaft gehauchtes H',short:'H/ɦ',word:'гора',de:'Berg',note:'Nicht deutsches G. Das harte G ist Ґ.'},
'Ґ':{lower:'ґ',ipa:'/ɡ/',sound:'hartes G wie in „Gast“',short:'G',word:'ґудзик',de:'Knopf',note:'Ґ = hartes G; Г = /ɦ/.'},
'Д':{lower:'д',ipa:'/d/',sound:'D wie in „Dach“',short:'D',word:'дім',de:'Haus',note:'Vertrauter Laut, neue Form.'},
'Е':{lower:'е',ipa:'/ɛ/',sound:'E wie in „Ecke“',short:'E',word:'екран',de:'Bildschirm',note:'Nicht mit Є verwechseln.'},
'Є':{lower:'є',ipa:'/jɛ/',sound:'je wie in „jetzt“',short:'JE',word:'єнот',de:'Waschbär',note:'Am Wortanfang ungefähr „je“.'},
'Ж':{lower:'ж',ipa:'/ʒ/',sound:'stimmhaftes Sch wie in „Garage“',short:'SCH stimmhaft',word:'жук',de:'Käfer',note:'Kontrast: Ж /ʒ/ ↔ Ш /ʃ/.'},
'З':{lower:'з',ipa:'/z/',sound:'stimmhaftes S wie in „Rose“',short:'S stimmhaft',word:'зуб',de:'Zahn',note:'З = /z/, С = /s/.'},
'И':{lower:'и',ipa:'/ɪ/',sound:'kurzes, offeneres I',short:'I/ɪ',word:'син',de:'Sohn',note:'Kein perfektes deutsches Gegenstück. Von І trennen.',audioIndex:1},
'І':{lower:'і',ipa:'/i/',sound:'klares I wie in „Igel“',short:'I',word:'ім’я',de:'Name',note:'І = klares /i/.'},
'Ї':{lower:'ї',ipa:'/ji/',sound:'ji',short:'JI',word:'їжа',de:'Essen',note:'Die zwei Punkte gehören dazu.'},
'Й':{lower:'й',ipa:'/j/',sound:'J wie in „Ja“',short:'J',word:'йогурт',de:'Joghurt',note:'Kurzes J.'},
'К':{lower:'к',ipa:'/k/',sound:'K wie in „Katze“',short:'K',word:'кіт',de:'Katze',note:'Form und Laut sind vertraut.'},
'Л':{lower:'л',ipa:'/l/',sound:'L wie in „Lampe“',short:'L',word:'лампа',de:'Lampe',note:'Vertrauter Laut, neue Form.'},
'М':{lower:'м',ipa:'/m/',sound:'M wie in „Mama“',short:'M',word:'мама',de:'Mama',note:'Form und Laut sind vertraut.'},
'Н':{lower:'н',ipa:'/n/',sound:'N wie in „Nase“',short:'N',word:'ніс',de:'Nase',note:'Sieht wie H aus, klingt N.'},
'О':{lower:'о',ipa:'/ɔ/',sound:'O wie in „Ofen“',short:'O',word:'око',de:'Auge',note:'Form und Laut sind vertraut.'},
'П':{lower:'п',ipa:'/p/',sound:'P wie in „Park“',short:'P',word:'парк',de:'Park',note:'Nicht mit Н oder Р verwechseln.'},
'Р':{lower:'р',ipa:'/r/',sound:'gerolltes R',short:'R',word:'рука',de:'Hand',note:'Sieht wie P aus, klingt R.'},
'С':{lower:'с',ipa:'/s/',sound:'scharfes S wie in „Hass“',short:'S',word:'сир',de:'Käse',note:'Sieht wie C aus, klingt S.'},
'Т':{lower:'т',ipa:'/t/',sound:'T wie in „Tag“',short:'T',word:'так',de:'Ja',note:'Großbuchstabe vertraut; Kleinbuchstabe separat prüfen.'},
'У':{lower:'у',ipa:'/u/',sound:'U wie in „Uhr“',short:'U',word:'урок',de:'Lektion',note:'Sieht wie Y aus, klingt U.'},
'Ф':{lower:'ф',ipa:'/f/',sound:'F wie in „Foto“',short:'F',word:'Франція',de:'Frankreich',note:'Neue Form, vertrauter Laut.'},
'Х':{lower:'х',ipa:'/x/',sound:'CH wie in „Bach“',short:'CH',word:'хата',de:'Haus',note:'Sieht wie X aus, klingt nicht „ks“.'},
'Ц':{lower:'ц',ipa:'/t͡s/',sound:'Z wie in „Zeit“',short:'TS/Z',word:'це',de:'dies',note:'Ц = ts, Ч = tsch.'},
'Ч':{lower:'ч',ipa:'/t͡ʃ/',sound:'tsch wie in „Tschüss“',short:'TSCH',word:'чай',de:'Tee',note:'Ч = tsch, Ц = ts.'},
'Ш':{lower:'ш',ipa:'/ʃ/',sound:'Sch wie in „Schule“',short:'SCH',word:'школа',de:'Schule',note:'Ш = sch; Щ ≈ schtsch.'},
'Щ':{lower:'щ',ipa:'/ʃt͡ʃ/',sound:'ungefähr sch + tsch',short:'SCHTSCH',word:'щука',de:'Hecht',note:'Bewusst gegen Ш trainieren.'},
'Ь':{lower:'ь',ipa:'—',sound:'kein eigener Laut',short:'WEICHHEITSZEICHEN',word:'кінь',de:'Pferd',note:'Ь macht den vorherigen Konsonanten weich.',audioIndex:3},
'Ю':{lower:'ю',ipa:'/ju/',sound:'ju wie in „Jubel“',short:'JU',word:'юнак',de:'junger Mann',note:'Am Wortanfang „ju“.'},
'Я':{lower:'я',ipa:'/ja/',sound:'ja',short:'JA',word:'яблуко',de:'Apfel',note:'Am Wortanfang „ja“.'}
};
const CONTRASTS=[['В','Б'],['Н','П'],['Р','П'],['С','З'],['У','В'],['Х','Г'],['Г','Ґ'],['І','И'],['Е','Є'],['Ж','Ш'],['Ш','Щ'],['Ц','Ч'],['Ї','Й'],['Б','Ь']];
const INTERVALS=[2*MIN,10*MIN,30*MIN,6*HOUR,DAY,3*DAY,7*DAY,14*DAY,30*DAY];
const KINDS=['visual','reverse','audio','lowercase','uppercase','contrast','trueFalse','memory','find','speed'];
const VARIANTS=['similar-find','visual-chaos','odd-one-out','pair-match','alphabet-order','nonsense-syllable','sound-contrast'];
function uniq(a){return [...new Set(a)]}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function shuffle(a,rng=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function todayFrom(now=Date.now()){return new Date(now).toISOString().slice(0,10)}
function freshKind(){return {seen:0,correct:0,wrong:0,totalMs:0,fastCorrect:0,lastAt:0}}
function freshLetter(){const kindStats={};KINDS.forEach(k=>kindStats[k]=freshKind());return {seen:0,correct:0,wrong:0,totalMs:0,answerCount:0,avgMs:0,lastAnswer:'',lastWrongAnswer:'',lastWrongAt:0,lastAt:0,correctStreak:0,intervalIndex:0,due:0,successDays:[],writeDays:[],confusions:{},kindStats,lapses:0,legacyStrength:0}}
function freshState(){const letters={};ALPHABET.forEach(c=>letters[c]=freshLetter());return {version:VERSION,createdAt:Date.now(),lastStudy:'',studyDays:[],streak:0,xp:0,letters,answerLog:[],examHistory:[],diagnostic:null,badges:[],masteryChecks:{final:[],fake:[],audio:[],retention:[]},settings:{audio:true}}}
function mergeLetter(old={}){const base=freshLetter(),out={...base,...old};out.successDays=uniq(Array.isArray(old.successDays)?old.successDays:[]);out.writeDays=uniq(Array.isArray(old.writeDays)?old.writeDays:[]);out.confusions={...(old.confusions||{})};out.kindStats={...base.kindStats};for(const k of KINDS)out.kindStats[k]={...base.kindStats[k],...((old.kindStats||{})[k]||{})};if(!old.kindStats&&((Number(old.correct)||0)+(Number(old.wrong)||0)>0)){const n=(Number(old.correct)||0)+(Number(old.wrong)||0);out.kindStats.visual={...out.kindStats.visual,seen:n,correct:Number(old.correct)||0,wrong:Number(old.wrong)||0,totalMs:Number(old.totalMs)||0,lastAt:Number(old.last)||0}}if(old.strength!=null&&out.legacyStrength===0)out.legacyStrength=Number(old.strength)||0;if(!out.answerCount&&out.seen)out.answerCount=Number(out.correct||0)+Number(out.wrong||0);if(!out.totalMs&&out.avgMs&&out.answerCount)out.totalMs=out.avgMs*out.answerCount;out.avgMs=out.answerCount?Math.round(out.totalMs/out.answerCount):0;return out}
function migrate(raw){const base=freshState();if(!raw||typeof raw!=='object')return base;const out={...base,...raw,version:VERSION,letters:{},masteryChecks:{...base.masteryChecks,...(raw.masteryChecks||{})},settings:{...base.settings,...(raw.settings||{})}};ALPHABET.forEach(c=>out.letters[c]=mergeLetter(raw.letters?.[c]||{}));out.answerLog=Array.isArray(raw.answerLog)?raw.answerLog.slice(-2500):[];out.examHistory=Array.isArray(raw.examHistory)?raw.examHistory.slice(-200):[];out.studyDays=uniq(Array.isArray(raw.studyDays)?raw.studyDays:(raw.lastStudy?[raw.lastStudy]:[])).sort();out.badges=uniq(Array.isArray(raw.badges)?raw.badges:[]);return out}
function touchStudy(state,now=Date.now()){const day=todayFrom(now);if(!state.studyDays.includes(day))state.studyDays.push(day);state.studyDays=uniq(state.studyDays).sort();const prev=state.lastStudy;if(prev!==day){if(prev){const delta=(new Date(day+'T12:00:00')-new Date(prev+'T12:00:00'))/DAY;state.streak=delta===1?(state.streak||0)+1:1}else state.streak=1;state.lastStudy=day}return state}
function kindCoverage(m){return KINDS.filter(k=>m.kindStats?.[k]?.correct>0).length}
function accuracy(m){const n=m.correct+m.wrong;return n?m.correct/n:0}
function speedFactor(m){if(m.correct<3||!m.avgMs)return .55;return clamp((3200-m.avgMs)/2200,0,1)}
function letterMastery(state,c,now=Date.now()){const m=state.letters[c],n=m.correct+m.wrong;if(!n)return 0;const acc=accuracy(m),evidence=clamp(n/12,0,1),coverage=clamp(kindCoverage(m)/5,0,1),ret=clamp((m.successDays?.length||0)/(HARD.has(c)?4:3),0,1),speed=speedFactor(m),writing=(m.writeDays?.length||0)>0?1:.4;let score=(acc*.38+coverage*.18+ret*.2+speed*.14+writing*.1)*evidence;const confusionTotal=Object.values(m.confusions||{}).reduce((a,b)=>a+Number(b||0),0);score-=Math.min(.12,confusionTotal/Math.max(20,n)*.22);if(m.due&&m.due<now-14*DAY)score*=.88;if(m.correctStreak===0&&m.wrong>0)score*=.9;return Math.round(clamp(score,0,1)*100)}
function letterStatus(state,c,now=Date.now()){const m=letterMastery(state,c,now);if(state.letters[c].seen===0)return 'Noch nicht gelernt';if(m>=85)return 'Sicher';if(m>=65)return 'Unsicher';return 'Problem'}
function fastThreshold(kind){return kind==='speed'||kind==='memory'?1400:kind==='visual'||kind==='reverse'?2200:3000}
function scheduleAfter(state,c,good,ms,kind='visual',now=Date.now()){const m=state.letters[c];if(!good){m.intervalIndex=Math.max(0,m.intervalIndex-2);m.due=now+INTERVALS[0];return m.due}const slow=ms>fastThreshold(kind)*1.6;if(slow)m.intervalIndex=Math.max(1,m.intervalIndex);else m.intervalIndex=Math.min(INTERVALS.length-1,m.intervalIndex+1);m.due=now+INTERVALS[m.intervalIndex];return m.due}
function recordAnswer(state,{letter,good,kind='visual',selected='',confusedWith='',ms=0,now=Date.now(),source='practice'}){if(!ALPHABET.includes(letter))throw new Error('Unknown letter '+letter);if(!KINDS.includes(kind))kind='visual';const m=state.letters[letter],ks=m.kindStats[kind]||(m.kindStats[kind]=freshKind()),day=todayFrom(now);touchStudy(state,now);m.seen++;m.answerCount++;m.lastAt=now;m.lastAnswer=String(selected||'');m.totalMs+=Math.max(0,Number(ms)||0);m.avgMs=m.answerCount?Math.round(m.totalMs/m.answerCount):0;ks.seen++;ks.lastAt=now;ks.totalMs+=Math.max(0,Number(ms)||0);if(good){m.correct++;m.correctStreak++;ks.correct++;if(ms>0&&ms<=fastThreshold(kind))ks.fastCorrect++;if(!m.successDays.includes(day))m.successDays.push(day);state.xp+=kind==='speed'?12:10}else{m.wrong++;m.correctStreak=0;m.lastWrongAnswer=String(selected||'');m.lastWrongAt=now;m.lapses++;ks.wrong++;state.xp+=1;if(confusedWith&&ALPHABET.includes(confusedWith)&&confusedWith!==letter)m.confusions[confusedWith]=(m.confusions[confusedWith]||0)+1}scheduleAfter(state,letter,good,ms,kind,now);state.answerLog.push({at:now,date:day,letter,good:!!good,kind,selected:String(selected||''),ms:Math.max(0,Number(ms)||0),source});state.answerLog=state.answerLog.slice(-2500);return state}
function recordWriting(state,c,now=Date.now()){const day=todayFrom(now),m=state.letters[c];if(!m.writeDays.includes(day))m.writeDays.push(day);touchStudy(state,now);state.xp+=4;return state}
function topConfusions(state,limit=10){const agg={};for(const c of ALPHABET){for(const [other,n] of Object.entries(state.letters[c].confusions||{})){const key=[c,other].sort().join(' ↔ ');agg[key]=(agg[key]||0)+Number(n||0)}}return Object.entries(agg).sort((a,b)=>b[1]-a[1]).slice(0,limit)}
function weakLetters(state,limit=10,now=Date.now()){return [...ALPHABET].sort((a,b)=>letterMastery(state,a,now)-letterMastery(state,b,now)||(state.letters[a].lastAt-state.letters[b].lastAt)).slice(0,limit)}
function errorLetters(state){return ALPHABET.filter(c=>state.letters[c].wrong>0).sort((a,b)=>state.letters[b].wrong-state.letters[a].wrong)}
function dueLetters(state,now=Date.now()){return ALPHABET.filter(c=>state.letters[c].seen>0&&state.letters[c].due<=now).sort((a,b)=>state.letters[a].due-state.letters[b].due)}
function secureLetters(state,now=Date.now()){return ALPHABET.filter(c=>letterMastery(state,c,now)>=85)}
function weightedPool(state,scope='standard',now=Date.now()){if(scope==='errors')return errorLetters(state).length?errorLetters(state):weakLetters(state,12,now);if(scope==='fake')return FAKE_FRIENDS;if(scope==='weak')return weakLetters(state,14,now);if(scope==='audio')return ALPHABET;if(scope==='speed')return secureLetters(state,now).length>=6?secureLetters(state,now):ALPHABET;const weak=weakLetters(state,12,now),errors=errorLetters(state).slice(0,10),due=dueLetters(state,now).slice(0,12),secure=secureLetters(state,now),normal=shuffle(ALPHABET).slice(0,12);return [...Array(3).fill(weak).flat(),...Array(2).fill(errors).flat(),...Array(2).fill(due).flat(),...Array(2).fill(normal).flat(),...secure.slice(0,8)]}
function pickLetter(state,scope,rng=Math.random,prev='',now=Date.now()){let pool=weightedPool(state,scope,now).filter(Boolean);if(!pool.length)pool=[...ALPHABET];let c=pool[Math.floor(rng()*pool.length)]||ALPHABET[0];if(c===prev&&pool.some(x=>x!==prev)){const alt=pool.filter(x=>x!==prev);c=alt[Math.floor(rng()*alt.length)]}return c}
function taskKindsFor(scope){if(scope==='audio')return ['audio'];if(scope==='speed')return ['speed','memory','visual'];if(scope==='fake')return ['visual','reverse','contrast','trueFalse','memory','find'];return ['visual','reverse','audio','lowercase','uppercase','contrast','trueFalse','memory','find','speed']}
function makeTask(letter,type,state,rng=Math.random){const d=DATA[letter],conf=SOUND_GROUPS[letter]||[];if(type==='contrast'&&!conf.length)type='visual';const options=()=>shuffle(uniq([letter,...conf,...shuffle(ALPHABET.filter(x=>x!==letter),rng)]).slice(0,4),rng);if(type==='visual'||type==='speed'||type==='memory')return {letter,type,prompt:'Welcher Laut gehört zu diesem Zeichen?',display:letter,correct:d.sound,options:shuffle(uniq([d.sound,...options().filter(x=>x!==letter).map(x=>DATA[x].sound)]).slice(0,4),rng)};if(type==='reverse')return {letter,type,prompt:`Welcher ukrainische Buchstabe entspricht „${d.sound}“?`,correct:letter,options:options()};if(type==='audio')return {letter,type,prompt:letter==='Ь'?'Hör das Referenzwort. Welches Zeichen markiert die Weichheit am Ende?':`Hör das Referenzwort. Welches Zeichen gehört an Position ${(d.audioIndex??0)+1}?`,correct:letter,options:options(),audioWord:d.word,audioIndex:d.audioIndex??0};if(type==='lowercase')return {letter,type,prompt:'Welcher Kleinbuchstabe gehört dazu?',display:letter,correct:d.lower,options:shuffle(uniq([d.lower,...options().filter(x=>x!==letter).map(x=>DATA[x].lower)]).slice(0,4),rng)};if(type==='uppercase')return {letter,type,prompt:'Welcher Großbuchstabe gehört dazu?',display:d.lower,correct:letter,options:options()};if(type==='contrast'){const other=conf[0]||options().find(x=>x!==letter);return {letter,type,prompt:`Welches Zeichen steht für „${d.sound}“?`,display:`${letter} · ${other}`,correct:letter,options:shuffle([letter,other],rng)}}if(type==='trueFalse'){const truth=rng()>.45,other=(conf[0]||options().find(x=>x!==letter)),shown=truth?d.sound:DATA[other].sound;return {letter,type,prompt:`Richtig oder falsch: ${letter} = ${shown}`,correct:truth?'Richtig':'Falsch',options:['Richtig','Falsch'],asserted:shown}}if(type==='find')return {letter,type,prompt:`Wähle ${letter}.`,correct:letter,options:options()};return makeTask(letter,'visual',state,rng)}
function variantizeTask(base,index,scope,rng=Math.random){if(scope==='audio'||scope==='speed'||scope==='diagnostic')return base;const c=base.letter,conf=SOUND_GROUPS[c]||[],pickOthers=n=>shuffle(ALPHABET.filter(x=>x!==c),rng).slice(0,n),slot=index%13;
  if(slot===2){return {letter:c,type:'find',variant:'visual-chaos',prompt:`Finde ${c} im Zeichenfeld.`,correct:c,options:shuffle(uniq([c,...conf,...pickOthers(7)]).slice(0,8),rng)}}
  if(slot===4){const partner=VOWELS[Math.floor(rng()*VOWELS.length)],first=rng()>.5,display=(first?c:partner)+(first?partner:c),pos=first?1:2;return {letter:c,type:'find',variant:'nonsense-syllable',display,prompt:`Unsinnssilbe „${DATA[display[0]].lower}${DATA[display[1]].lower}“: Welcher Buchstabe steht an Position ${pos}?`,correct:c,options:shuffle(uniq([c,...conf,...pickOthers(3)]).slice(0,4),rng)}}
  if(slot===6){const other=conf[0]||pickOthers(1)[0],wrongLower=DATA[other].lower,correct=`${c} – ${DATA[c].lower}`;return {letter:c,type:'lowercase',variant:'pair-match',display:c,prompt:'Welches Groß-/Klein-Paar gehört korrekt zusammen?',correct,options:shuffle([correct,`${c} – ${wrongLower}`,`${other} – ${DATA[c].lower}`,`${other} – ${wrongLower}`],rng)}}
  if(slot===8){const group=uniq([c,...conf]).slice(0,3),unrelated=ALPHABET.find(x=>!group.includes(x)&&!(SOUND_GROUPS[c]||[]).includes(x))||pickOthers(1)[0];return {letter:c,type:'contrast',variant:'odd-one-out',display:shuffle([...group,unrelated],rng).join(' · '),prompt:`Welches Zeichen passt NICHT zur Verwechslungsgruppe rund um ${c}?`,correct:unrelated,options:shuffle([...group,unrelated],rng)}}
  if(slot===10&&scope!=='fake'){const opts=shuffle(uniq([c,...pickOthers(3)]).slice(0,4),rng),correct=[...opts].sort((a,b)=>ALPHABET.indexOf(a)-ALPHABET.indexOf(b))[0];return {letter:correct,type:'find',variant:'alphabet-order',prompt:'Welcher dieser Buchstaben kommt im ukrainischen Alphabet zuerst?',correct,options:opts}}
  if(slot===12&&conf.length){const other=conf[0];return {letter:c,type:'contrast',variant:'sound-contrast',display:`${c} · ${other}`,prompt:`Welches Zeichen gehört zum Laut „${DATA[c].short}“?`,correct:c,options:shuffle([c,other],rng)}}
  return base
}
function buildExam(state,{size=30,scope='standard',feedback='learning',rng=Math.random,now=Date.now()}={}){const tasks=[],kinds=taskKindsFor(scope);let prev='';for(let i=0;i<size;i++){const c=pickLetter(state,scope,rng,prev,now),type=kinds[Math.floor(rng()*kinds.length)],base=makeTask(c,type,state,rng);tasks.push(variantizeTask(base,i,scope,rng));prev=c}return {size,scope,feedback,tasks}}
function alternateType(type){const map={visual:'reverse',reverse:'visual',audio:'visual',lowercase:'uppercase',uppercase:'lowercase',contrast:'reverse',trueFalse:'visual',memory:'reverse',find:'visual',speed:'contrast'};return map[type]||'visual'}
function repairTask(task,state,rng=Math.random){return {...makeTask(task.letter,alternateType(task.type),state,rng),repair:true,fromType:task.type}}
function buildDiagnostic(state,{size=50,rng=Math.random}={}){const tasks=shuffle(ALPHABET,rng).map(c=>makeTask(c,'visual',state,rng));const extras=[];while(extras.length<Math.max(0,size-33)){const c=FAKE_FRIENDS[extras.length%FAKE_FRIENDS.length]||ALPHABET[extras.length%33];const t=extras.length%2?'reverse':'contrast';extras.push(makeTask(c,t,state,rng))}return {size:tasks.length+extras.length,scope:'diagnostic',feedback:'real',tasks:shuffle([...tasks,...extras],rng)}}
function recordExam(state,summary){state.examHistory.unshift({...summary});state.examHistory=state.examHistory.slice(0,200);return state}
function addMasteryCheck(state,type,summary){state.masteryChecks[type]=state.masteryChecks[type]||[];state.masteryChecks[type].push(summary);state.masteryChecks[type]=state.masteryChecks[type].slice(-20);return state}
function distinctPassDays(checks,pred){return new Set((checks||[]).filter(pred).map(x=>x.date)).size}
function letterReady(state,c,now=Date.now()){const m=state.letters[c],mastery=letterMastery(state,c,now),days=uniq(m.successDays||[]).length,coverage=kindCoverage(m);return mastery>=85&&days>=(HARD.has(c)?4:3)&&coverage>=5&&(m.writeDays||[]).length>=1&&accuracy(m)>=.9}
function averageRecognitionMs(state){const xs=[];for(const c of ALPHABET){const k=state.letters[c].kindStats.visual;if(k.correct>=3&&k.totalMs>0)xs.push(k.totalMs/k.seen)}return xs.length?Math.round(xs.reduce((a,b)=>a+b,0)/xs.length):0}
function mastered(state,now=Date.now()){const allLetters=ALPHABET.every(c=>letterReady(state,c,now));const finals=distinctPassDays(state.masteryChecks.final,x=>x.accuracy>=.95&&x.total>=50)>=2;const fake=(state.masteryChecks.fake||[]).some(x=>x.accuracy===1&&x.total>=20);const audio=(state.masteryChecks.audio||[]).some(x=>x.accuracy>=.95&&x.total>=30);const retention=distinctPassDays(state.masteryChecks.retention,x=>x.accuracy>=.95)>=1||state.studyDays.length>=7;const avg=averageRecognitionMs(state),speed=avg===0?false:avg<=2500;return {done:allLetters&&finals&&fake&&audio&&retention&&speed,allLetters,finals,fake,audio,retention,speed,avgRecognitionMs:avg,readyCount:ALPHABET.filter(c=>letterReady(state,c,now)).length}}
function statsToday(state,now=Date.now()){const day=todayFrom(now),rows=state.answerLog.filter(x=>x.date===day),correct=rows.filter(x=>x.good).length,ms=rows.filter(x=>x.ms>0).map(x=>x.ms);return {questions:rows.length,correct,wrong:rows.length-correct,accuracy:rows.length?Math.round(correct/rows.length*100):0,avgMs:ms.length?Math.round(ms.reduce((a,b)=>a+b,0)/ms.length):0,exams:state.examHistory.filter(x=>x.date===day).length}}
function summaryForLetter(state,c,now=Date.now()){const m=state.letters[c],conf=Object.entries(m.confusions||{}).sort((a,b)=>b[1]-a[1])[0]||['',0],types={};for(const k of KINDS){const s=m.kindStats[k],n=s.correct+s.wrong;types[k]=n?Math.round(s.correct/n*100):0}return {letter:c,mastery:letterMastery(state,c,now),status:letterStatus(state,c,now),seen:m.seen,correct:m.correct,wrong:m.wrong,accuracy:Math.round(accuracy(m)*100),avgMs:m.avgMs,lastAnswer:m.lastAnswer,lastWrongAnswer:m.lastWrongAnswer,lastWrongAt:m.lastWrongAt,topConfusion:conf[0],topConfusionCount:conf[1],nextDue:m.due,correctStreak:m.correctStreak,successDays:m.successDays.length,typeCoverage:kindCoverage(m),types}}
root.AlphabetCoreV2=Object.freeze({VERSION,DAY,HOUR,MIN,ALPHABET,LEARN_ORDER,FAKE_FRIENDS,HARD,DATA,SOUND_GROUPS,CONTRASTS,KINDS,VARIANTS,INTERVALS,uniq,clamp,shuffle,todayFrom,freshState,migrate,touchStudy,accuracy,letterMastery,letterStatus,recordAnswer,recordWriting,topConfusions,weakLetters,errorLetters,dueLetters,secureLetters,makeTask,variantizeTask,buildExam,buildDiagnostic,repairTask,recordExam,addMasteryCheck,mastered,statsToday,summaryForLetter,letterReady,averageRecognitionMs});
})(typeof globalThis!=='undefined'?globalThis:this);
