import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const errors=[];const assert=(ok,msg)=>{if(!ok)errors.push(msg)};const compile=(code,name)=>{try{new vm.Script(code,{filename:name})}catch(e){errors.push(`${name}: ${e.message}`)}};
for(const file of fs.readdirSync(root).filter(x=>/^ukrainischkurs-.*\.js$/.test(x)).concat('ukrainisch-lernen-sw.js'))compile(read(file),file);
for(const file of ['ukrainisch-lernen.html','ukrainischkurs-app.html','index.html']){let i=0;for(const m of read(file).matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi))compile(m[1],`${file} inline-${++i}`)}
try{JSON.parse(read('ukrainisch-lernen.webmanifest'))}catch(e){errors.push(`Manifest: ${e.message}`)}
const base=read('ukrainisch-lernen.html'),app=read('ukrainischkurs-app.html');assert(app===base.replace('</body>','<script src="./ukrainischkurs-v2-loader.js"></script>\n</body>'),'App-Hülle ist nicht deterministisch aktuell');
const loader=read('ukrainischkurs-v2-loader.js');assert(loader.includes("const VERSION='45'"),'Loader ist nicht v45');for(const t of ['designer-alphabet.js?v=3','fashion-bridge.js?v=1','learning-core.js?v=4','a1-exam.js?v=2','selftest.js?v=34'])assert(loader.includes(t),`Loader vermisst ${t}`);assert(loader.indexOf('learning-core.js')<loader.indexOf('fashion-bridge.js'),'Fashion-Brücke lädt vor ihrem Lernkern');
const sw=read('ukrainisch-lernen-sw.js');assert(sw.includes("const VERSION='45'"),'Service Worker ist nicht v45');assert(sw.includes("'./ukrainischkurs-fashion-bridge.js'"),'Fashion-Brücke fehlt im Offline-Cache');assert(sw.includes('else if(stableLoader)event.respondWith(freshAssetResponse(event.request,url))'),'Stable Loader ist nicht network-first');assert(!sw.includes('requestedVersion&&requestedVersion!==VERSION'),'Modulversionen werden wieder mit globaler Version verwechselt');
const designer=read('ukrainischkurs-designer-alphabet.js');assert(designer.includes('const VERSION=3'),'Designer-Alphabet ist nicht v3');assert(designer.includes('rotatingCues:true')&&designer.includes('function rotateCue(letter)'),'Modeanker rotieren nicht');assert((designer.match(/brands:\[/g)||[]).length===33,'Nicht alle 33 Buchstaben besitzen eine definierte Marken-/Modebank');for(const brand of ['Alexander McQueen','Ann Demeulemeester','Alaïa','Acne Studios','Balenciaga','Balmain','Bottega Veneta','Vivienne Westwood','Valentino','Versace','Jean Paul Gaultier','Jacquemus','Givenchy','Yohji Yamamoto','Kenzo','Kiko Kostadinov','Maison Margiela','Mugler','Ottolinger','Prada','Raf Simons','Rick Owens','Rundholz','Saint Laurent','Sacai','Undercover','Fendi','Chanel'])assert(designer.includes(brand),`Fashion-Anker fehlt: ${brand}`);assert(designer.includes('memoryAnchors:Object.values(A).reduce')&&designer.includes('brandAnchors:brandCount'),'Designer-Modul exportiert Umfang der Anker nicht');assert(designer.includes("quiz.anchorCorrect===3&&quiz.soundCorrect===3"),'3+3 Zeichen-/Laut-Nachweis fehlt');for(const trap of ["'В':'Sieht wie deutsches B aus","'Н':'Sieht wie deutsches H aus","'Р':'Sieht wie deutsches P aus","'С':'Sieht wie deutsches C aus","'У':'Sieht wie deutsches Y aus","'Х':'Sieht wie deutsches X aus"])assert(designer.includes(trap),`Falscher Freund fehlt: ${trap}`);assert(designer.includes('alphabetGate:false'),'Fashion-Merkhilfe darf Alphabet-Mastery nicht ersetzen');
const fashion=read('ukrainischkurs-fashion-bridge.js');assert(fashion.includes('const VERSION=1'),'Fashion-Brücke ist nicht v1');assert((fashion.match(/title:'/g)||[]).length===14,'Fashion-Brücke hat nicht 14 Themen');assert((fashion.match(/\['[^']+','[^']+'\]/g)||[]).length>=56,'Fashion-Brücke hat zu wenig Vokabel-/Satzpaare');for(const t of ['Artikel · Oberteile','Schuhe & Accessoires','Materialien','Farben','Größe & Passform','Zustand','Preis & Rabatt','Kaufen & Verkaufen','Original & Marke','Listing & Details','Versand','Mini-Sätze · Verkauf'])assert(fashion.includes(t),`Fashion-Thema fehlt: ${t}`);for(const w of ['куртка','піджак','штани','спідниця','сукня','взуття','черевики','шкіра','бавовна','вовна','розмір','стан','ціна','знижка','купити','продати','покупець','продавець','оригінал','справжній','логотип','опис','етикетка','посилка','доставка'])assert(fashion.includes(w),`Fashion-Wort fehlt: ${w}`);assert(fashion.includes("core.isUnlocked('alphabet.mastery')")&&fashion.includes('optional:true')&&fashion.includes('alphabetDependency:true'),'Fashion-Brücke ist nicht sauber optional an Alphabet-Mastery gekoppelt');assert(fashion.includes('topics:TOPICS.length')&&fashion.includes("items:TOPICS.reduce((n,t)=>n+t.items.length,0)"),'Fashion-Brücke exportiert Umfang nicht');
const core=read('ukrainischkurs-learning-core.js');assert(core.includes("'a1.exam':{requires:['immersion.transfer']")&&core.includes("'a1.final':{requires:['a1.exam']"),'A1-Gates beschädigt');assert(core.includes("s.a1Exam?.domains?.[k]?.passed&&!!s.a1Exam?.domains?.[k]?.confirmed"),'A1-Doppelpass-Gate beschädigt');
const exam=read('ukrainischkurs-a1-exam.js');assert(exam.includes('doublePass:true')&&exam.includes('generatedForms:true')&&exam.includes('maxListeningPlays:2'),'A1-Prüfungsstrenge beschädigt');assert(exam.includes('officialCertificate:false')&&exam.includes('cefrAligned:true'),'A1-Status ist nicht transparent');
const selftest=read('ukrainischkurs-selftest.js');assert(selftest.includes('Laufzeit-Selbsttest v34')&&selftest.includes('version===45')&&selftest.includes('designer?.version===3')&&selftest.includes('UKRAINIAN_FASHION_BRIDGE'),'Selbsttest ist nicht auf v45/Fashion aktualisiert');
if(errors.length){console.error(`VALIDIERUNG FEHLGESCHLAGEN (${errors.length})`);errors.forEach(e=>console.error('- '+e));process.exit(1)}
console.log('VALIDIERUNG OK: v45 mit rotierendem Designer-Alphabet v3, umfangreichem Marken-/Modeankernetz, 14 Fashion-Mikrothemen mit 56 Einheiten, optionaler Alphabet-abhängiger Fashion-Brücke, stabilem Offline-Pfad und unverändert strenger CEFR-A1-Prüfung geprüft.');