import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),errors=[];
const assert=(ok,msg)=>{if(!ok)errors.push(msg)};
const compile=(code,name)=>{try{new vm.Script(code,{filename:name})}catch(e){errors.push(`${name}: ${e.message}`)}};
const modules=['ukrainischkurs-native-audio.js','ukrainischkurs-pronunciation.js','ukrainischkurs-pronunciation-mastery.js','ukrainischkurs-quality-hardening.js','ukrainischkurs-adaptive-alphabet.js','ukrainischkurs-alphabet-proof.js','ukrainischkurs-reading-bridge.js','ukrainischkurs-reading-transfer.js','ukrainischkurs-adaptive-srs.js','ukrainischkurs-learning-core.js','ukrainischkurs-foundation-expansion.js','ukrainischkurs-a1-expansion-2.js','ukrainischkurs-a1-grammar-bridge.js','ukrainischkurs-time-bridge.js','ukrainischkurs-genitive-bridge.js','ukrainischkurs-word-stress.js','ukrainischkurs-human-sentence-audio.js','ukrainischkurs-human-listening.js','ukrainischkurs-speaking-bridge.js','ukrainischkurs-immersion-transfer.js','ukrainischkurs-open-dialogue.js','ukrainischkurs-conversation-chain.js','ukrainischkurs-free-reading-transfer.js','ukrainischkurs-comprehension-lab.js','ukrainischkurs-active-production.js','ukrainischkurs-grammar-spiral.js','ukrainischkurs-story-lab.js','ukrainischkurs-dictation.js','ukrainischkurs-a1-cando.js','ukrainischkurs-uk-keyboard.js','ukrainischkurs-dynamic-course-ui.js','ukrainischkurs-skill-profile.js','ukrainischkurs-selftest.js'];
const standalone=['ukrainischkurs-v2-loader.js',...modules,'ukrainisch-lernen-sw.js'];
for(const file of standalone){assert(fs.existsSync(path.join(root,file)),`${file} fehlt`);if(fs.existsSync(path.join(root,file)))compile(read(file),file)}
const combined=[1,2,3,4,5].map(n=>read(`ukrainischkurs-v2.part${n}`)).join('');compile(combined,'ukrainischkurs-v2.part1–5');
for(const htmlFile of ['ukrainisch-lernen.html','ukrainischkurs-app.html','index.html']){const html=read(htmlFile);let i=0;for(const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi))compile(m[1],`${htmlFile} inline-script-${++i}`)}
try{JSON.parse(read('ukrainisch-lernen.webmanifest'))}catch(e){errors.push(`ukrainisch-lernen.webmanifest: ${e.message}`)}

const loader=read('ukrainischkurs-v2-loader.js');
for(const f of modules)assert(loader.includes(f),`Loader bindet ${f} nicht ein`);
assert(loader.includes("const VERSION='34'"),'Loader ist nicht auf v34');
assert(loader.includes('evalFree:true'),'Loader kennzeichnet eval-freien Modus nicht');assert(!/\beval\s*\(/.test(loader),'Loader verwendet wieder eval()');
for(const token of ['learning-core.js?v=1','foundation-expansion.js?v=2','a1-grammar-bridge.js?v=2','time-bridge.js?v=1','genitive-bridge.js?v=1','word-stress.js?v=3','human-sentence-audio.js?v=3','human-listening.js?v=2','speaking-bridge.js?v=2','immersion-transfer.js?v=2','open-dialogue.js?v=2','conversation-chain.js?v=2','free-reading-transfer.js?v=2','comprehension-lab.js?v=3','active-production.js?v=3','a1-cando.js?v=6','skill-profile.js?v=1','selftest.js?v=23'])assert(loader.includes(token),`Loader vermisst ${token}`);
assert(loader.indexOf('adaptive-srs.js')<loader.indexOf('learning-core.js'),'Lernkern lädt vor dem SRS');
assert(loader.indexOf('learning-core.js')<loader.indexOf('a1-grammar-bridge.js'),'Grammatik-Brücke lädt vor dem Lernkern');
assert(loader.indexOf('a1-grammar-bridge.js')<loader.indexOf('time-bridge.js'),'Zeit-Brücke lädt vor Grammatik-Brücke');
assert(loader.indexOf('time-bridge.js')<loader.indexOf('genitive-bridge.js'),'Genitiv-Brücke lädt vor Zeit-Brücke');
assert(loader.indexOf('human-sentence-audio.js')<loader.indexOf('human-listening.js'),'Human-Listening lädt vor Human-Audio');
assert(loader.indexOf('human-listening.js')<loader.indexOf('speaking-bridge.js'),'Sprechbrücke lädt vor Human-Listening');
assert(loader.indexOf('speaking-bridge.js')<loader.indexOf('immersion-transfer.js'),'Immersion lädt vor Sprechbrücke');
assert(loader.indexOf('immersion-transfer.js')<loader.indexOf('a1-cando.js'),'Can-do lädt vor Immersion');
assert(loader.indexOf('dynamic-course-ui.js')<loader.indexOf('skill-profile.js'),'Skill-Profil lädt vor dynamischer UI');
assert(loader.indexOf('skill-profile.js')<loader.indexOf('selftest.js'),'Selbsttest lädt vor Skill-Profil');

const sw=read('ukrainisch-lernen-sw.js');for(const f of modules)assert(sw.includes(`'./${f}'`),`Offline-Cache enthält ${f} nicht`);assert(sw.includes("ukrainischkurs-joel-v34"),'Service Worker ist nicht auf v34');assert(sw.includes("event.request.mode==='navigate'||event.request.destination==='document'"),'Service Worker begrenzt App-Shell-Fallback nicht auf Dokumentnavigation');assert(sw.includes("new Response('Offline-Asset nicht verfügbar'"),'Service Worker hat keinen sauberen Asset-Fehler');assert(!/catch\(\(\)=>caches\.match\('\.\/ukrainischkurs-app\.html'\)\)/.test(sw),'Service Worker liefert bei jedem Assetfehler wieder HTML');
const app=read('ukrainischkurs-app.html');assert(app.includes('ukrainischkurs-v2-loader.js?v=34'),'App-Loader ist nicht v34');assert(app.includes('ukrainisch-lernen.html?v=34'),'Basis-App ist nicht v34');

const part1=read('ukrainischkurs-v2.part1'),expected='А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я';assert(part1.includes(`const ORDER = '${expected}'.split(' ')`),'Alphabet-Reihenfolge stimmt nicht');assert((part1.match(/'[^']+':\{pair:/g)||[]).length===33,'LETTER_INFO enthält nicht 33 Einträge');
const hard=read('ukrainischkurs-quality-hardening.js');assert(hard.includes('confirmedTargets'),'Aussprache-Gate hat keine per-Laut-Bestätigung');assert(hard.includes('targets.every(l=>g.confirmedTargets.includes(l))'),'Aussprache-Gate akzeptiert nicht jeden Ziellaut');
const native=read('ukrainischkurs-native-audio.js'),keys=[...native.matchAll(/^\s*'([А-ЯІЇЄҐЬ])':\{file:/gmu)].map(m=>m[1]);assert(keys.length===33&&new Set(keys).size===33,'Audioabdeckung ist nicht exakt 33');
const adaptive=read('ukrainischkurs-adaptive-alphabet.js');assert(adaptive.includes('retentionCount()===33'),'33-Zeichen-Retention fehlt');assert(adaptive.includes('threshold:32'),'32/33-Schwelle fehlt');
const proof=read('ukrainischkurs-alphabet-proof.js');assert(proof.includes('session.correct>=19'),'95%-Alphabet-Proof fehlt');assert(proof.includes('successDays(l)>=3'),'3-Tage-Schwierigkeiten fehlen');
const reading=read('ukrainischkurs-reading-transfer.js');assert((reading.match(/\{kind:'/g)||[]).length>=30,'Lese-Transfer-Pool zu klein');assert(reading.includes('session.correct>=18'),'Lese-Transfer verlangt nicht 18/20');
const srs=read('ukrainischkurs-adaptive-srs.js');for(const token of ['meta.ease','meta.lapses','meta.interval','meta.leech','repairPending','90'])assert(srs.includes(token),`Adaptive-SRS-Bestandteil ${token} fehlt`);

const learningCore=read('ukrainischkurs-learning-core.js');assert(learningCore.includes('const VERSION=1'),'Lernkern ist nicht v1');for(const token of ["const SKILLS=['reading','listening','writing','speaking','grammar']",'function normalize(value,opts={})','function accepts(value,answers,opts={})','function introductionDay(needle,opts={})','function recordSession(meta={})','function weakest()','function isUnlocked(id)',"'alphabet.mastery'","'grammar.location-direction'","'grammar.time'","'grammar.genitive'","'listening.human'","'speaking.sentences'","'immersion.transfer'","'a1.final'",'seedLegacy()','window.UKRAINIAN_LEARNING_CORE'])assert(learningCore.includes(token),`Lernkern vermisst ${token}`);assert(learningCore.includes("replace(/[ʼ’‘'`]/g,'’')"),'Lernkern normalisiert Apostrophvarianten nicht zentral');assert(learningCore.includes("normalize('NFC')"),'Lernkern nutzt keine NFC-Normalisierung');assert(learningCore.includes('st.history.length>40'),'Skill-Historie ist nicht begrenzt');

const foundation=read('ukrainischkurs-foundation-expansion.js');assert(foundation.includes('const VERSION=2'),'Foundation ist nicht v2');for(const token of ['Мені: Gefühl und Bedarf','Мені ist die Dativform','Де? → Ortsform','в Україні','у Києві','в готелі'])assert(foundation.includes(token),`Foundation vermisst ${token}`);
const grammarBridge=read('ukrainischkurs-a1-grammar-bridge.js');assert(grammarBridge.includes('const VERSION=2'),'Grammatik-Brücke ist nicht v2');for(const token of ['Куди ти йдеш?','Я в магазині','Я йду в магазин','кава → каву','аптека → аптеку','Я їду в Київ',"core.recordSession({skills:['grammar','writing']",'core.accepts(value,answers)'])assert(grammarBridge.includes(token),`Grammatik-Brücke vermisst ${token}`);assert(grammarBridge.includes('st.passed=perfect'),'Grammatik-Brücke verlangt keinen fehlerfreien Durchgang');
const time=read('ukrainischkurs-time-bridge.js');for(const token of ['вчора','завтра','Я був у готелі','Я була у готелі','Я буду працювати','Ти будеш працювати?','Що ти будеш робити завтра?'])assert(time.includes(token),`Zeit-Brücke vermisst ${token}`);assert(time.includes('st.passed=perfect'),'Zeit-Brücke verlangt keinen fehlerfreien Durchgang');
const genitive=read('ukrainischkurs-genitive-bridge.js');for(const token of ['У мене немає води','У мене немає квитка','У мене немає грошей','Чого немає?','Звідки ти?','Я з України','п’ять гривень','п’ять квитків'])assert(genitive.includes(token),`Genitiv-Brücke vermisst ${token}`);assert(genitive.includes('st.passed=perfect'),'Genitiv-Brücke verlangt keinen fehlerfreien Durchgang');
const stress=read('ukrainischkurs-word-stress.js');assert(stress.includes('const VERSION=3'),'Wortbetonung ist nicht v3');assert(stress.includes("core.introductionDay(entry.plain,{cardOnly:true})"),'Wortbetonung nutzt die zentrale Curriculum-Suche nicht');assert((stress.match(/source:'https:\/\//g)||[]).length===12,'Wortbetonung enthält nicht 12 Quellen');

const human=read('ukrainischkurs-human-sentence-audio.js');assert(human.includes('const VERSION=3'),'Human-Audio ist nicht v3');assert((human.match(/file:'Uk-/g)||[]).length===12,'Human-Audio enthält nicht exakt 12 verifizierte Dateieinträge');assert((human.match(/license:'CC BY 3\.0 US'/g)||[]).length>=3,'Human-Audio enthält keine Lizenzmetadaten');assert(human.includes("new CustomEvent('ukrainian-audio-source'"),'Human-Audio meldet die tatsächlich verwendete Quelle nicht');assert(human.includes("dataset.audioSource='tts-fallback'"),'Human-Audio kennzeichnet TTS-Fallback nicht');assert(human.includes("dataset.audioSource='human'"),'Human-Audio kennzeichnet echte menschliche Wiedergabe nicht');assert(human.includes('has:text=>MAP.has(norm(text))'),'Human-Audio exportiert keine Zielprüfung');assert(human.includes('const failOnce=()=>{if(failed)return;failed=true'),'Human-Audio schützt den TTS-Fallback nicht vor Doppelaufruf');assert(!human.includes('native:true'),'Human-Audio behauptet unbelegt Native-Status');
const listening=read('ukrainischkurs-human-listening.js');assert(listening.includes('const VERSION=2'),'Human-Listening ist nicht v2');for(const token of ['вода','аптека','магазин','автобус','лікар','тато','брат','туалет','будь ласка','Я не знаю','Німеччина','Україна',"core.recordSession({skills:['listening','writing']",'core.accepts(value,[wanted])'])assert(listening.includes(token),`Human-Listening vermisst ${token}`);assert((listening.match(/^\s*\['/gm)||[]).length>=3,'Human-Listening enthält zu wenige Tage');assert(listening.includes("session.correct===session.items.length"),'Human-Listening verlangt nicht 4/4');assert(listening.includes('typing-input'),'Human-Listening nutzt keine freie ukrainische Eingabe');assert(listening.includes("window.addEventListener('ukrainian-audio-source'"),'Human-Listening erfasst Human/TTS-Quelle nicht');assert(listening.includes("Menschliche Aufnahme"),'Human-Listening zeigt menschliche Quelle nicht an');assert(listening.includes("System-TTS-Fallback"),'Human-Listening zeigt TTS-Fallback nicht an');assert(listening.includes('session.listened=false;session.source=\'loading\''),'Human-Listening wartet nicht auf bestätigten Audiostart');assert(listening.includes('speak(text,button)'),'Human-Listening startet Audio nicht direkt aus dem Tap-Handler');assert(!listening.includes('setTimeout(()=>speak(text,button)'),'Human-Listening verliert auf Safari die User-Gesture durch verzögertes Audio');assert(!listening.includes('data-hl-choice'),'Human-Listening enthält unerwartete Antwortauswahl');

const speaking=read('ukrainischkurs-speaking-bridge.js');assert(speaking.includes('const VERSION=2'),'Sprechbrücke ist nicht v2');for(const token of ['Sprechen: wichtige Hilfe-Sätze','Sprechen: Ort, Richtung, Genitiv','Sprechen: gestern und morgen','Abschluss-Review','Я не розумію','Мені потрібна допомога','Я йду в магазин','У мене немає води','Вчора я був у готелі','Завтра я буду працювати','skillRecorded',"core.recordSession({skills:['speaking']"])assert(speaking.includes(token),`Sprechbrücke vermisst ${token}`);assert(speaking.includes('navigator.mediaDevices?.getUserMedia'),'Sprechbrücke nutzt keine lokale Mikrofonaufnahme');assert(speaking.includes('window.MediaRecorder'),'Sprechbrücke prüft MediaRecorder nicht');assert(speaking.includes('new Audio(rec.url)'),'Sprechbrücke bietet kein Rückhören der eigenen Aufnahme');assert(speaking.includes('session.heardBefore<1||session.heardAfter<1'),'A/B-Vergleich verlangt nicht zwei Referenzhörungen');assert(speaking.includes('session.recorded&&session.replayed'),'Aufnahme kann ohne Rückhören bestätigt werden');assert(speaking.includes('session.manualSpoken'),'Sprechbrücke hat keinen transparenten Fallback');assert(speaking.includes('Keine automatische Akzentnote'),'Sprechbrücke behauptet automatische Akzentmessung');

const immersion=read('ukrainischkurs-immersion-transfer.js');assert(immersion.includes('const VERSION=2'),'Immersionsphase ist nicht v2');assert((immersion.match(/title:'Immersion /g)||[]).length===6,'Immersionsphase enthält nicht sechs aktive Szenarien');assert((immersion.match(/,de:'/g)||[]).length===5,'Deutsche Notfallhilfe ist nicht auf fünf Antworten des ersten Tages begrenzt');for(const token of ["mode:'audio'","mode:'memory'","mode:'chain'","mode:'memory-chain'",'Питання приховане','Роль прихована','Immersion 5 · 8-Zug-Gespräch','Immersion 6 · фінальна місія',"core.isUnlocked('immersion.transfer')",'function skillsFor(sc)',"core.recordSession({skills:skillsFor(sc)",'dependencyGate:true','germanSolutionHintsAfterDay1:false'])assert(immersion.includes(token),`Immersionsphase vermisst ${token}`);assert(immersion.includes('maxTurns:Math.max'),'Immersionsphase exportiert maximale Gesprächslänge nicht');assert((immersion.match(/q:'/g)||[]).length>=37,'Immersionsphase enthält zu wenige freie Transferfragen');assert(immersion.includes('WEEKLY_REVIEW_DAYS.splice'),'Immersionsphase aktualisiert Review-/Abschlussstruktur nicht');assert(immersion.includes('typing-input'),'Immersionsphase nutzt keine freie ukrainische Eingabe');assert(!immersion.includes('data-im-choice'),'Immersionsphase enthält unerwartete Antwortbuttons');

const dialogue=read('ukrainischkurs-open-dialogue.js');assert(dialogue.includes('const VERSION=2'),'Open Dialogue ist nicht v2');assert((dialogue.match(/context:/g)||[]).length===16,'Open Dialogue enthält nicht 16 Transferfragen');assert(dialogue.includes('typing-input'),'Open Dialogue verlangt keine freie Antwort');
const chain=read('ukrainischkurs-conversation-chain.js');assert(chain.includes('const VERSION=2'),'Gesprächskette ist nicht v2');assert((chain.match(/hint:/g)||[]).length===14,'Gesprächsketten enthalten nicht 14 Gesprächszüge');for(const token of ['speakingStart+2','Звідки ти?','Чого у тебе немає?','Де ти був учора?','Що ти будеш робити завтра?','maxTurns:Math.max'])assert(chain.includes(token),`Gesprächskette v2 vermisst ${token}`);assert(chain.includes('historyHtml()'),'Gesprächskette zeigt keinen Verlauf');assert(chain.includes('st.passed=perfect'),'Gesprächskette verlangt keinen fehlerfreien Durchgang');
const freeRead=read('ukrainischkurs-free-reading-transfer.js');assert(freeRead.includes('const VERSION=2'),'Freier Lese-Transfer ist nicht v2');assert((freeRead.match(/text:'/g)||[]).length===3,'Freier Lese-Transfer enthält nicht drei Kurztexte');assert(freeRead.includes("phase='questions'"),'Freier Lese-Transfer blendet Text nicht aus');assert(freeRead.includes('Der Text bleibt ausgeblendet'),'Text bleibt bei Fragen nicht verborgen');assert(freeRead.includes('st.passed=perfect'),'Freier Lese-Transfer verlangt nicht 3/3');assert(freeRead.includes("core.recordSession({skills:['reading','writing']"),'Freier Lese-Transfer schreibt keine Skill-Evidenz');
const comp=read('ukrainischkurs-comprehension-lab.js');assert(comp.includes('const VERSION=3'),'Verständnis-Labor ist nicht v3');assert(comp.includes('session.correct>=2'),'Verständnis-Labor verlangt nicht 2/3');assert(comp.includes("skills:[kind]"),'Verständnis-Labor trennt Lesen/Hören im Skill-Profil nicht');
const prod=read('ukrainischkurs-active-production.js');assert(prod.includes('const VERSION=3'),'Freie Produktion ist nicht v3');assert(prod.includes('session.correct>=4&&!session.criticalMiss'),'Freie Produktion verlangt nicht 4/5 plus kritische Aufgabe');assert(prod.includes("core.recordSession({skills:['writing','grammar']"),'Freie Produktion schreibt keine zentrale Skill-Evidenz');assert(prod.includes('core.accepts(value,[answer])'),'Freie Produktion nutzt die zentrale Bewertung nicht');
const grammar=read('ukrainischkurs-grammar-spiral.js');assert(grammar.includes('const VERSION=3'),'Grammatik-Spirale ist nicht v3');
const stories=read('ukrainischkurs-story-lab.js');assert(stories.includes('Text ausblenden & prüfen'),'Story Lab blendet Text nicht aus');
const dict=read('ukrainischkurs-dictation.js');assert(dict.includes('session.heard=true'),'Diktat prüft Anhören nicht');
const cando=read('ukrainischkurs-a1-cando.js');assert(cando.includes('const VERSION=6'),'Can-do ist nicht v6');assert((cando.match(/\{mode:'/g)||[]).length===16,'Can-do hat nicht 16 Aufgaben');assert((cando.match(/mode:'type'/g)||[]).length===12,'Can-do hat nicht 12 freie Eingaben');for(const token of ['Я йду в магазин','Я в магазині','Вчора я був у готелі','Завтра я буду працювати','У мене немає води','!session.genitiveMiss',"core.isUnlocked('a1.final')",'modeCorrect:{type:0,audio:0}',"skills:['writing','grammar']","skills:['listening']"])assert(cando.includes(token),`Can-do vermisst ${token}`);
const keyboard=read('ukrainischkurs-uk-keyboard.js');assert(keyboard.includes('const VERSION=2'),'Eingabehilfe ist nicht v2');assert(!keyboard.includes('data-answer'),'Eingabehilfe enthält Lösungshinweise');
const dyn=read('ukrainischkurs-dynamic-course-ui.js');for(const token of ['function courseLength(){return Array.isArray(D)?D.length:0}','Tag ${n} · Abschluss','von ${courseLength()} Kurstagen fertig','UKRAINIAN_DYNAMIC_COURSE_UI'])assert(dyn.includes(token),`Dynamische Kursanzeige vermisst ${token}`);
const profile=read('ukrainischkurs-skill-profile.js');assert(profile.includes('const VERSION=1'),'Skill-Profil ist nicht v1');for(const token of ['core.profile()','core.weakest()','Adaptives Skill-Profil','5 Bereiche','window.UKRAINIAN_SKILL_PROFILE'])assert(profile.includes(token),`Skill-Profil vermisst ${token}`);assert(!profile.includes('data-skill-choice'),'Skill-Profil lässt den Lernenden unerwartet den Lernweg wählen');
const self=read('ukrainischkurs-selftest.js');for(const token of ['UKRAINIAN_LEARNING_CORE','UKRAINIAN_SKILL_PROFILE','core?.skills.length===5',"core?.isUnlocked==='function'",'UKRAINIAN_IMMERSION_TRANSFER','D.length>=90'])assert(self.includes(token),`Selbsttest vermisst ${token}`);assert(self.includes('window.UKRAINIAN_COURSE_LOADER?.version===34'),'Selbsttest prüft Loader v34 nicht');assert(self.includes('Number(s.humanListening.version)>=2'),'Selbsttest prüft Human-Listening v2 nicht');assert(self.includes('Number(s.a1GrammarBridge.version)>=2'),'Selbsttest prüft Grammatik-Brücke v2 nicht');assert(self.includes('Number(s.a1CanDo.version)>=6'),'Selbsttest prüft Can-do v6 nicht');assert(self.includes('window.UKRAINIAN_IMMERSION_TRANSFER?.dependencyGate===true'),'Selbsttest prüft Kompetenz-Gate der Immersion nicht');

if(errors.length){console.error(`VALIDIERUNG FEHLGESCHLAGEN (${errors.length})`);for(const e of errors)console.error('- '+e);process.exit(1)}
console.log('VALIDIERUNG OK: Syntax, Loader/Cache v34, zentraler Lernkern mit gemeinsamer Unicode-Bewertung, Curriculum-Meilensteinen und fünf Skillkanälen, 33-Laut-Mastery, Grammatik-/Zeit-/Genitivbrücken, Human-Audio/Diktat, Satz-A/B-Sprechen, 6-Tage-Immersion mit Kompetenz-Gates, ca. 90-Tage-Pfad, Skill-Profil, sicherer Offline-Fallback und Can-do v6 geprüft.');