import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const errors=[];const assert=(ok,msg)=>{if(!ok)errors.push(msg)};const compile=(code,name)=>{try{new vm.Script(code,{filename:name})}catch(e){errors.push(`${name}: ${e.message}`)}};
for(const file of fs.readdirSync(root).filter(x=>/^ukrainischkurs-.*\.js$/.test(x)).concat('ukrainisch-lernen-sw.js'))compile(read(file),file);
for(const file of ['ukrainisch-lernen.html','ukrainischkurs-app.html','index.html']){let i=0;for(const m of read(file).matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi))compile(m[1],`${file} inline-${++i}`)}
try{JSON.parse(read('ukrainisch-lernen.webmanifest'))}catch(e){errors.push(`Manifest: ${e.message}`)}
const base=read('ukrainisch-lernen.html'),app=read('ukrainischkurs-app.html');assert(app===base.replace('</body>','<script src="./ukrainischkurs-v2-loader.js"></script>\n</body>'),'App-Hülle ist nicht deterministisch aktuell');
const loader=read('ukrainischkurs-v2-loader.js');assert(loader.includes("const VERSION='46'"),'Loader ist nicht v46');for(const t of ['designer-alphabet.js?v=3','fashion-bridge.js?v=1','resale-practice.js?v=1','learning-core.js?v=4','a1-exam.js?v=2','selftest.js?v=35'])assert(loader.includes(t),`Loader vermisst ${t}`);assert(loader.indexOf('learning-core.js')<loader.indexOf('fashion-bridge.js')&&loader.indexOf('fashion-bridge.js')<loader.indexOf('resale-practice.js'),'Additive Fashion-/Resale-Reihenfolge ist falsch');
const sw=read('ukrainisch-lernen-sw.js');assert(sw.includes("const VERSION='46'"),'Service Worker ist nicht v46');for(const asset of ["'./ukrainischkurs-fashion-bridge.js'","'./ukrainischkurs-resale-practice.js'","'./ukrainischkurs-a1-exam.js'"])assert(sw.includes(asset),`Offline-Asset fehlt: ${asset}`);assert(sw.includes('else if(stableLoader)event.respondWith(freshAssetResponse(event.request,url))'),'Stable Loader ist nicht network-first');assert(!sw.includes('requestedVersion&&requestedVersion!==VERSION'),'Modulversionen werden wieder mit globaler Version verwechselt');
const designer=read('ukrainischkurs-designer-alphabet.js');assert(designer.includes('const VERSION=3')&&designer.includes('rotatingCues:true'),'Designer-Alphabet v3/Rotation fehlt');assert(designer.includes('alphabetGate:false'),'Designer-Merkhilfe darf Alphabet-Mastery nicht ersetzen');
const fashion=read('ukrainischkurs-fashion-bridge.js');assert(fashion.includes('const VERSION=1'),'Fashion-Brücke ist nicht v1');assert((fashion.match(/title:'/g)||[]).length===14,'Fashion-Brücke hat nicht 14 Themen');assert(fashion.includes('optional:true')&&fashion.includes('alphabetDependency:true'),'Fashion-Brücke ist nicht optional/Alphabet-abhängig');
const resale=read('ukrainischkurs-resale-practice.js');assert(resale.includes('const VERSION=1'),'Resale-Praxis ist nicht v1');assert((resale.match(/title:'/g)||[]).length===15,'Resale-Praxis hat nicht 15 Situationen');assert((resale.match(/\['[^']+','[^']+',\[/g)||[]).length===60,'Resale-Praxis hat nicht 60 Antwortzüge');for(const t of ['Artikel beschreiben','Größe & Passform','Material','Zustand','Defekt ehrlich erklären','Preis nennen','Preis verhandeln','Maße','Original & Echtheit','Fotos & Details','Verfügbarkeit','Reservieren','Versand','Versand ins Ausland','Kompletter Käuferchat'])assert(resale.includes(t),`Resale-Situation fehlt: ${t}`);for(const phrase of ['Я продаю куртку.','Розмір M.','Це шкіра.','Стан хороший.','Так, є маленький дефект.','Ціна сто євро.','Так, можу зробити знижку.','Довжина сімдесят сантиметрів.','Так, це оригінал.','Так, є фото логотипа.','Так, товар ще є.','Так, до завтра.','Відправлю завтра.','Так, можу відправити в Німеччину.'])assert(resale.includes(phrase),`Praxisantwort fehlt: ${phrase}`);assert(resale.includes('core.accepts(value,task[2])'),'Resale-Praxis nutzt nicht die zentrale Freitextbewertung');assert(resale.includes("core.isUnlocked('alphabet.mastery')"),'Resale-Praxis startet ohne Alphabet-Abhängigkeit');assert(resale.includes('optional:true')&&resale.includes('personalized:true')&&resale.includes('centralScoring:true')&&resale.includes('systemAudio:true'),'Resale-Praxis exportiert ihre Additiv-/Bewertungsmerkmale nicht');assert(resale.includes('Math.min(SCENARIOS.length,1+Math.floor(Math.max(0,d-14)/5))'),'Resale-Situationen werden nicht schrittweise freigeschaltet');assert(!resale.includes("s.a1CanDo.passed=")&&!resale.includes("s.a1Exam="),'Resale-Praxis darf A1-Status nicht manipulieren');
const core=read('ukrainischkurs-learning-core.js');assert(core.includes("'a1.exam':{requires:['immersion.transfer']")&&core.includes("'a1.final':{requires:['a1.exam']"),'A1-Gates beschädigt');assert(core.includes("s.a1Exam?.domains?.[k]?.passed&&!!s.a1Exam?.domains?.[k]?.confirmed"),'A1-Doppelpass-Gate beschädigt');
const exam=read('ukrainischkurs-a1-exam.js');assert(exam.includes('doublePass:true')&&exam.includes('generatedForms:true')&&exam.includes('maxListeningPlays:2'),'A1-Prüfungsstrenge beschädigt');assert(exam.includes('officialCertificate:false')&&exam.includes('cefrAligned:true'),'A1-Status ist nicht transparent');
const selftest=read('ukrainischkurs-selftest.js');assert(selftest.includes('Laufzeit-Selbsttest v35')&&selftest.includes('version===46')&&selftest.includes('UKRAINIAN_FASHION_BRIDGE')&&selftest.includes('UKRAINIAN_RESALE_PRACTICE'),'Selbsttest ist nicht auf v46/Fashion/Resale aktualisiert');
if(errors.length){console.error(`VALIDIERUNG FEHLGESCHLAGEN (${errors.length})`);errors.forEach(e=>console.error('- '+e));process.exit(1)}
console.log('VALIDIERUNG OK: v46 ergänzt die bestehende Fashion-Schicht ausschließlich additiv um 15 Disorder119-Resale-Situationen mit 60 aktiven Antwortzügen, zentraler Freitextbewertung, Käufer-Systemaudio, schrittweiser Freischaltung und Offline-Cache; vorhandene Fashion-Bridge und strenge CEFR-A1-Gates bleiben unverändert erhalten.');