import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),errors=[];
const assert=(ok,msg)=>{if(!ok)errors.push(msg)},compile=(code,name)=>{try{new vm.Script(code,{filename:name})}catch(e){errors.push(`${name}: ${e.message}`)}};
const standalone=['ukrainischkurs-v2-loader.js','ukrainischkurs-native-audio.js','ukrainischkurs-pronunciation.js','ukrainischkurs-pronunciation-mastery.js','ukrainischkurs-quality-hardening.js','ukrainischkurs-adaptive-alphabet.js','ukrainischkurs-alphabet-proof.js','ukrainischkurs-reading-bridge.js','ukrainischkurs-reading-transfer.js','ukrainischkurs-adaptive-srs.js','ukrainischkurs-foundation-expansion.js','ukrainischkurs-a1-expansion-2.js','ukrainischkurs-word-stress.js','ukrainischkurs-comprehension-lab.js','ukrainischkurs-active-production.js','ukrainischkurs-grammar-spiral.js','ukrainischkurs-story-lab.js','ukrainischkurs-dictation.js','ukrainischkurs-a1-cando.js','ukrainischkurs-uk-keyboard.js','ukrainischkurs-selftest.js','ukrainisch-lernen-sw.js'];
for(const file of standalone){assert(fs.existsSync(path.join(root,file)),`${file} fehlt`);if(fs.existsSync(path.join(root,file)))compile(read(file),file)}
const combined=[1,2,3,4,5].map(n=>read(`ukrainischkurs-v2.part${n}`)).join('');compile(combined,'ukrainischkurs-v2.part1–5');
for(const htmlFile of ['ukrainisch-lernen.html','ukrainischkurs-app.html','index.html']){const html=read(htmlFile);let i=0;for(const match of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi))compile(match[1],`${htmlFile} inline-script-${++i}`)}
try{JSON.parse(read('ukrainisch-lernen.webmanifest'))}catch(e){errors.push(`ukrainisch-lernen.webmanifest: ${e.message}`)}
const required=['ukrainischkurs-native-audio.js','ukrainischkurs-pronunciation.js','ukrainischkurs-pronunciation-mastery.js','ukrainischkurs-quality-hardening.js','ukrainischkurs-adaptive-alphabet.js','ukrainischkurs-alphabet-proof.js','ukrainischkurs-reading-bridge.js','ukrainischkurs-reading-transfer.js','ukrainischkurs-adaptive-srs.js','ukrainischkurs-foundation-expansion.js','ukrainischkurs-a1-expansion-2.js','ukrainischkurs-word-stress.js','ukrainischkurs-comprehension-lab.js','ukrainischkurs-active-production.js','ukrainischkurs-grammar-spiral.js','ukrainischkurs-story-lab.js','ukrainischkurs-dictation.js','ukrainischkurs-a1-cando.js','ukrainischkurs-uk-keyboard.js','ukrainischkurs-selftest.js'];
const loader=read('ukrainischkurs-v2-loader.js');for(const f of required)assert(loader.includes(f),`Loader bindet ${f} nicht ein`);assert(loader.includes("const VERSION='26'"),'Loader ist nicht auf v26');assert(loader.includes('evalFree:true'),'Loader kennzeichnet eval-freien Modus nicht');assert(!/\beval\s*\(/.test(loader),'Loader verwendet wieder eval()');assert(loader.includes('foundation-expansion.js?v=2'),'Foundation v2 ist nicht aktiv');assert(loader.includes('word-stress.js?v=2'),'Wortbetonung v2 ist nicht aktiv');assert(loader.includes('selftest.js?v=15'),'Selbsttest v15 ist nicht aktiv');assert(loader.indexOf('a1-expansion-2.js')<loader.indexOf('word-stress.js'),'Wortbetonung lädt vor den A1-Wortdaten');
const sw=read('ukrainisch-lernen-sw.js');for(const f of required)assert(sw.includes(`'./${f}'`),`Offline-Cache enthält ${f} nicht`);assert(sw.includes("ukrainischkurs-joel-v26"),'Service Worker ist nicht auf v26');
const app=read('ukrainischkurs-app.html');assert(app.includes('ukrainischkurs-v2-loader.js?v=26'),'App-Loader ist nicht auf v26');assert(app.includes('ukrainisch-lernen.html?v=26'),'Basis-App ist nicht auf v26');
const part1=read('ukrainischkurs-v2.part1'),expected='А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я';assert(part1.includes(`const ORDER = '${expected}'.split(' ')`),'Alphabet-Reihenfolge stimmt nicht');assert((part1.match(/'[^']+':\{pair:/g)||[]).length===33,'LETTER_INFO enthält nicht 33 Einträge');
const hard=read('ukrainischkurs-quality-hardening.js');assert(hard.includes('confirmedTargets'),'Aussprache-Gate hat keine per-Laut-Bestätigung');assert(hard.includes('targets.every(l=>g.confirmedTargets.includes(l))'),'Aussprache-Gate akzeptiert nicht jeden Ziellaut');
const native=read('ukrainischkurs-native-audio.js'),keys=[...native.matchAll(/^\s*'([А-ЯІЇЄҐЬ])':\{file:/gmu)].map(m=>m[1]);assert(keys.length===33&&new Set(keys).size===33,'Audioabdeckung ist nicht exakt 33');
const adaptive=read('ukrainischkurs-adaptive-alphabet.js');assert(adaptive.includes('retentionCount()===33'),'33-Zeichen-Retention fehlt');assert(adaptive.includes('threshold:32'),'32/33-Schwelle fehlt');
const proof=read('ukrainischkurs-alphabet-proof.js');assert(proof.includes('session.correct>=19'),'95%-Proof fehlt');assert(proof.includes('successDays(l)>=3'),'3-Tage-Schwierigkeiten fehlen');
const bridge=read('ukrainischkurs-reading-bridge.js');for(const token of ['приві́т','дя́кую','кінь','м’ясо','їжа'])assert(bridge.includes(token),`Lese-Brücke vermisst ${token}`);
const transfer=read('ukrainischkurs-reading-transfer.js');assert((transfer.match(/\{kind:'/g)||[]).length>=30,'Lese-Transfer-Pool zu klein');assert(transfer.includes('session.correct>=18'),'Lese-Transfer verlangt nicht 18/20');
const srs=read('ukrainischkurs-adaptive-srs.js');for(const token of ['meta.ease','meta.lapses','meta.interval','meta.leech','repairPending','90'])assert(srs.includes(token),`Adaptive-SRS-Bestandteil ${token} fehlt`);
const foundation=read('ukrainischkurs-foundation-expansion.js');assert(foundation.includes('const VERSION=2'),'Foundation ist nicht v2');for(const token of ['Мені: Gefühl und Bedarf','Мені ist die Dativform','Де? → Ortsform','в Україні','у Києві','в готелі'])assert(foundation.includes(token),`Foundation v2 vermisst ${token}`);assert(foundation.includes('rule(8'),'Ortsfall hat keinen eigenen Anwendungstest');assert(foundation.includes('LESSONS.forEach(x=>D.push(x))'),'Foundation wird nicht angehängt');
const a12=read('ukrainischkurs-a1-expansion-2.js');assert(a12.includes('LESSONS.forEach(x=>D.push(x))'),'A1-Erweiterung 2 wird nicht angehängt');
const stress=read('ukrainischkurs-word-stress.js');const stressEntries=(stress.match(/\{plain:/g)||[]).length;assert(stress.includes('const VERSION=2'),'Wortbetonung ist nicht v2');assert(stressEntries>=12,`Wortbetonung enthält nur ${stressEntries} Einträge`);for(const token of ['по́тяг','авто́бус','зупи́нка','лі́кар','апте́ка','допомо́га','Украї́ні','ма́ма','сестра́','батьки́','розумі́ю','магази́н'])assert(stress.includes(token),`Wortbetonung vermisst ${token}`);assert(stress.includes('function introDay(entry)'),'Wortbetonung ermittelt Einführungstag nicht dynamisch');assert(stress.includes("cards.some(card=>(' '+canon(card?.[0])+' ').includes(' '+needle+' '))"),'Wortbetonung koppelt sich nicht an echte Kurskarten');assert(!/\bmin:\d+/.test(stress),'Wortbetonung verwendet wieder starre Tagesnummern');assert(stress.includes('newToday().length>0||reviewDay()'),'Wortbetonung ist nicht bei Einführung und Review verpflichtend');assert(stress.includes('source:'),'Wortbetonung enthält keine Quellenmetadaten');
const comp=read('ukrainischkurs-comprehension-lab.js');assert(comp.includes('session.correct>=2'),'Verständnis-Labor verlangt nicht 2/3');
const prod=read('ukrainischkurs-active-production.js');assert(prod.includes('session.correct>=4&&!session.criticalMiss'),'Freie Produktion verlangt nicht 4/5 plus kritische Aufgabe');
const grammar=read('ukrainischkurs-grammar-spiral.js');assert(grammar.includes('const VERSION=3'),'Grammatik-Spirale ist nicht v3');
const stories=read('ukrainischkurs-story-lab.js');assert(stories.includes('const VERSION=3'),'Story Lab ist nicht v3');assert(stories.includes('Text ausblenden & prüfen'),'Story Lab blendet Text nicht aus');
const dict=read('ukrainischkurs-dictation.js');assert(dict.includes('const VERSION=3'),'Diktat ist nicht v3');assert(dict.includes('session.heard=true'),'Diktat prüft Anhören nicht');
const cando=read('ukrainischkurs-a1-cando.js');assert((cando.match(/\{mode:'/g)||[]).length===16,'Can-do hat nicht 16 Aufgaben');assert(cando.includes('session.correct>=13&&!session.criticalMiss'),'Can-do-Schwelle fehlt');
const keyboard=read('ukrainischkurs-uk-keyboard.js');assert(keyboard.includes('const VERSION=2'),'Eingabehilfe ist nicht v2');assert(!keyboard.includes('data-answer'),'Eingabehilfe enthält Lösungshinweise');
const self=read('ukrainischkurs-selftest.js');for(const token of ['s.foundationExpansion','s.wordStress','UKRAINIAN_COURSE_LOADER','evalFree'])assert(self.includes(token),`Selbsttest vermisst ${token}`);assert(self.includes('window.UKRAINIAN_COURSE_LOADER?.version===26'),'Selbsttest prüft Loader v26 nicht');assert(self.includes('Number(s.foundationExpansion.version)>=2'),'Selbsttest prüft Foundation v2 nicht');assert(self.includes('Number(s.wordStress.version)>=2'),'Selbsttest prüft Wortbetonung v2 nicht');
if(errors.length){console.error(`VALIDIERUNG FEHLGESCHLAGEN (${errors.length})`);for(const e of errors)console.error('- '+e);process.exit(1)}
console.log('VALIDIERUNG OK: Syntax, Loader/Cache v26, Alphabet-Mastery, per-Laut-Aussprachegate, Foundation v2 mit Dativ/Ortsfall, dynamische verifizierte Wortbetonung v2, adaptives SRS, freie Produktion und Can-do geprüft.');