import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),errors=[];
const assert=(ok,msg)=>{if(!ok)errors.push(msg)};
const compile=(code,name)=>{try{new vm.Script(code,{filename:name})}catch(e){errors.push(`${name}: ${e.message}`)}};
const modules=['ukrainischkurs-native-audio.js','ukrainischkurs-pronunciation.js','ukrainischkurs-pronunciation-mastery.js','ukrainischkurs-quality-hardening.js','ukrainischkurs-adaptive-alphabet.js','ukrainischkurs-alphabet-proof.js','ukrainischkurs-reading-bridge.js','ukrainischkurs-reading-transfer.js','ukrainischkurs-adaptive-srs.js','ukrainischkurs-learning-core.js','ukrainischkurs-foundation-expansion.js','ukrainischkurs-a1-expansion-2.js','ukrainischkurs-a1-grammar-bridge.js','ukrainischkurs-time-bridge.js','ukrainischkurs-genitive-bridge.js','ukrainischkurs-word-stress.js','ukrainischkurs-human-sentence-audio.js','ukrainischkurs-human-listening.js','ukrainischkurs-speaking-bridge.js','ukrainischkurs-immersion-transfer.js','ukrainischkurs-open-dialogue.js','ukrainischkurs-conversation-chain.js','ukrainischkurs-free-reading-transfer.js','ukrainischkurs-comprehension-lab.js','ukrainischkurs-active-production.js','ukrainischkurs-grammar-spiral.js','ukrainischkurs-story-lab.js','ukrainischkurs-dictation.js','ukrainischkurs-adaptive-review.js','ukrainischkurs-a1-cando.js','ukrainischkurs-uk-keyboard.js','ukrainischkurs-dynamic-course-ui.js','ukrainischkurs-skill-profile.js','ukrainischkurs-selftest.js'];
const standalone=['ukrainischkurs-v2-loader.js',...modules,'ukrainisch-lernen-sw.js'];
for(const file of standalone){assert(fs.existsSync(path.join(root,file)),`${file} fehlt`);if(fs.existsSync(path.join(root,file)))compile(read(file),file)}
const combined=[1,2,3,4,5].map(n=>read(`ukrainischkurs-v2.part${n}`)).join('');compile(combined,'ukrainischkurs-v2.part1–5');
for(const htmlFile of ['ukrainisch-lernen.html','ukrainischkurs-app.html','index.html']){const html=read(htmlFile);let i=0;for(const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi))compile(m[1],`${htmlFile} inline-script-${++i}`)}
try{JSON.parse(read('ukrainisch-lernen.webmanifest'))}catch(e){errors.push(`ukrainisch-lernen.webmanifest: ${e.message}`)}

const loader=read('ukrainischkurs-v2-loader.js');
for(const f of modules)assert(loader.includes(f),`Loader bindet ${f} nicht ein`);
assert(loader.includes("const VERSION='35'"),'Loader ist nicht auf v35');assert(loader.includes('evalFree:true'),'Loader kennzeichnet eval-freien Modus nicht');assert(!/\beval\s*\(/.test(loader),'Loader verwendet wieder eval()');
for(const token of ['learning-core.js?v=2','a1-grammar-bridge.js?v=2','time-bridge.js?v=2','genitive-bridge.js?v=2','word-stress.js?v=3','human-listening.js?v=2','speaking-bridge.js?v=2','immersion-transfer.js?v=2','open-dialogue.js?v=3','conversation-chain.js?v=3','free-reading-transfer.js?v=2','comprehension-lab.js?v=4','active-production.js?v=4','grammar-spiral.js?v=4','dictation.js?v=4','adaptive-review.js?v=1','a1-cando.js?v=6','skill-profile.js?v=2','selftest.js?v=24'])assert(loader.includes(token),`Loader vermisst ${token}`);
assert(loader.indexOf('adaptive-srs.js')<loader.indexOf('learning-core.js'),'Lernkern lädt vor dem SRS');assert(loader.indexOf('learning-core.js')<loader.indexOf('a1-grammar-bridge.js'),'Grammatik-Brücke lädt vor Lernkern');assert(loader.indexOf('time-bridge.js')<loader.indexOf('genitive-bridge.js'),'Genitiv lädt vor Zeit-Brücke');assert(loader.indexOf('human-listening.js')<loader.indexOf('speaking-bridge.js'),'Sprechbrücke lädt vor Human-Listening');assert(loader.indexOf('speaking-bridge.js')<loader.indexOf('immersion-transfer.js'),'Immersion lädt vor Sprechbrücke');assert(loader.indexOf('dictation.js')<loader.indexOf('adaptive-review.js'),'Adaptiver Review lädt vor Diktat');assert(loader.indexOf('adaptive-review.js')<loader.indexOf('a1-cando.js'),'Can-do lädt vor adaptivem Review');assert(loader.indexOf('dynamic-course-ui.js')<loader.indexOf('skill-profile.js'),'Skill-Profil lädt vor dynamischer UI');assert(loader.indexOf('skill-profile.js')<loader.indexOf('selftest.js'),'Selbsttest lädt vor Skill-Profil');

const sw=read('ukrainisch-lernen-sw.js');for(const f of modules)assert(sw.includes(`'./${f}'`),`Offline-Cache enthält ${f} nicht`);assert(sw.includes("ukrainischkurs-joel-v35"),'Service Worker ist nicht auf v35');assert(sw.includes("event.request.mode==='navigate'||event.request.destination==='document'"),'Service Worker begrenzt App-Shell-Fallback nicht auf Navigation');assert(sw.includes("new Response('Offline-Asset nicht verfügbar'"),'Service Worker hat keinen sauberen Asset-Fehler');assert(!/catch\(\(\)=>caches\.match\('\.\/ukrainischkurs-app\.html'\)\)/.test(sw),'Service Worker liefert bei Assetfehlern wieder HTML');
const app=read('ukrainischkurs-app.html');assert(app.includes('ukrainischkurs-v2-loader.js?v=35'),'App-Loader ist nicht v35');assert(app.includes('ukrainisch-lernen.html?v=35'),'Basis-App ist nicht v35');

const part1=read('ukrainischkurs-v2.part1'),expected='А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я';assert(part1.includes(`const ORDER = '${expected}'.split(' ')`),'Alphabet-Reihenfolge stimmt nicht');assert((part1.match(/'[^']+':\{pair:/g)||[]).length===33,'LETTER_INFO enthält nicht 33 Einträge');
const hard=read('ukrainischkurs-quality-hardening.js');assert(hard.includes('confirmedTargets'),'Aussprache-Gate hat keine per-Laut-Bestätigung');assert(hard.includes('targets.every(l=>g.confirmedTargets.includes(l))'),'Aussprache-Gate akzeptiert nicht jeden Ziellaut');
const native=read('ukrainischkurs-native-audio.js'),keys=[...native.matchAll(/^\s*'([А-ЯІЇЄҐЬ])':\{file:/gmu)].map(m=>m[1]);assert(keys.length===33&&new Set(keys).size===33,'Audioabdeckung ist nicht exakt 33');
const adaptiveAlphabet=read('ukrainischkurs-adaptive-alphabet.js');assert(adaptiveAlphabet.includes('retentionCount()===33'),'33-Zeichen-Retention fehlt');assert(adaptiveAlphabet.includes('threshold:32'),'32/33-Schwelle fehlt');
const proof=read('ukrainischkurs-alphabet-proof.js');assert(proof.includes('session.correct>=19'),'95%-Alphabet-Proof fehlt');assert(proof.includes('successDays(l)>=3'),'3-Tage-Schwierigkeiten fehlen');
const reading=read('ukrainischkurs-reading-transfer.js');assert((reading.match(/\{kind:'/g)||[]).length>=30,'Lese-Transfer-Pool zu klein');assert(reading.includes('session.correct>=18'),'Lese-Transfer verlangt nicht 18/20');
const srs=read('ukrainischkurs-adaptive-srs.js');for(const token of ['meta.ease','meta.lapses','meta.interval','meta.leech','repairPending','90'])assert(srs.includes(token),`Adaptive-SRS-Bestandteil ${token} fehlt`);

const core=read('ukrainischkurs-learning-core.js');assert(core.includes('const VERSION=2'),'Lernkern ist nicht v2');for(const token of ["const SKILLS=['reading','listening','writing','speaking','grammar']",'function normalize(value,opts={})','function accepts(value,answers,opts={})','function introductionDay(needle,opts={})','function isIntroduced(needle,opts={})','function recordSession(meta={})','function rankedSkills(minSessions=1)','function focusForDay(','function reviewFocus()','focusHistory','rotateGap','function isUnlocked(id)',"'grammar.location-direction'","'grammar.time'","'grammar.genitive'","'listening.human'","'speaking.sentences'","'immersion.transfer'","'a1.final'",'window.UKRAINIAN_LEARNING_CORE'])assert(core.includes(token),`Lernkern vermisst ${token}`);assert(core.includes("replace(/[ʼ’‘'`]/g,'’')"),'Lernkern normalisiert Apostrophvarianten nicht');assert(core.includes("normalize('NFC')"),'Lernkern nutzt kein NFC');assert(core.includes('st.history.length>40'),'Skill-Historie ist nicht begrenzt');assert(core.includes('keys.length>30'),'Review-Fokus-Historie ist nicht begrenzt');assert(core.includes('!WEEKLY_REVIEW_DAYS.includes(day)'),'Review-Fokus wird außerhalb von Review-Tagen erzeugt');

const foundation=read('ukrainischkurs-foundation-expansion.js');assert(foundation.includes('const VERSION=2'),'Foundation ist nicht v2');for(const t of ['Мені: Gefühl und Bedarf','Де? → Ortsform','в Україні','у Києві','в готелі'])assert(foundation.includes(t),`Foundation vermisst ${t}`);
const grammarBridge=read('ukrainischkurs-a1-grammar-bridge.js');assert(grammarBridge.includes('const VERSION=2'),'Grammatik-Brücke ist nicht v2');for(const t of ['Куди ти йдеш?','Я в магазині','Я йду в магазин','кава → каву','Я їду в Київ',"core.recordSession({skills:['grammar','writing']",'core.accepts(value,answers)'])assert(grammarBridge.includes(t),`Grammatik-Brücke vermisst ${t}`);assert(grammarBridge.includes('st.passed=perfect'),'Grammatik-Brücke verlangt keinen fehlerfreien Durchgang');
const time=read('ukrainischkurs-time-bridge.js');assert(time.includes('const VERSION=2'),'Zeit-Brücke ist nicht v2');for(const t of ['Я був у готелі','Я була у готелі','Я буду працювати','Ти будеш працювати?','Що ти будеш робити завтра?',"core.recordSession({skills:['grammar','writing']",'core.accepts(v,a)'])assert(time.includes(t),`Zeit-Brücke vermisst ${t}`);
const genitive=read('ukrainischkurs-genitive-bridge.js');assert(genitive.includes('const VERSION=2'),'Genitiv-Brücke ist nicht v2');for(const t of ['У мене немає води','У мене немає квитка','Я з України','п’ять гривень','п’ять квитків',"core.recordSession({skills:['grammar','writing']",'core.accepts(v,a)'])assert(genitive.includes(t),`Genitiv-Brücke vermisst ${t}`);
const stress=read('ukrainischkurs-word-stress.js');assert(stress.includes('const VERSION=3'),'Wortbetonung ist nicht v3');assert(stress.includes("core.introductionDay(entry.plain,{cardOnly:true})"),'Wortbetonung nutzt Curriculum-Suche nicht');assert((stress.match(/source:'https:\/\//g)||[]).length===12,'Wortbetonung enthält nicht 12 Quellen');

const human=read('ukrainischkurs-human-sentence-audio.js');assert(human.includes('const VERSION=3'),'Human-Audio ist nicht v3');assert((human.match(/file:'Uk-/g)||[]).length===12,'Human-Audio enthält nicht 12 verifizierte Dateien');assert(human.includes("new CustomEvent('ukrainian-audio-source'"),'Human-Audio meldet Quelle nicht');assert(human.includes("dataset.audioSource='tts-fallback'"),'TTS-Fallback wird nicht gekennzeichnet');assert(!human.includes('native:true'),'Human-Audio behauptet unbelegt Native-Status');
const listening=read('ukrainischkurs-human-listening.js');assert(listening.includes('const VERSION=2'),'Human-Listening ist nicht v2');assert(listening.includes("core.recordSession({skills:['listening','writing']"),'Human-Listening schreibt keine Skill-Evidenz');assert(listening.includes('core.accepts(value,[wanted])'),'Human-Listening nutzt zentrale Bewertung nicht');assert(!listening.includes('data-hl-choice'),'Human-Listening enthält Antwortauswahl');
const speaking=read('ukrainischkurs-speaking-bridge.js');assert(speaking.includes('const VERSION=2'),'Sprechbrücke ist nicht v2');assert(speaking.includes('navigator.mediaDevices?.getUserMedia'),'Sprechbrücke nutzt keine Mikrofonaufnahme');assert(speaking.includes('new Audio(rec.url)'),'Sprechbrücke bietet kein Rückhören');assert(speaking.includes('Keine automatische Akzentnote'),'Sprechbrücke behauptet automatische Akzentmessung');assert(speaking.includes("core.recordSession({skills:['speaking']"),'Sprechbrücke schreibt keine Sprech-Evidenz');

const immersion=read('ukrainischkurs-immersion-transfer.js');assert(immersion.includes('const VERSION=2'),'Immersion ist nicht v2');assert((immersion.match(/title:'Immersion /g)||[]).length===6,'Immersion enthält nicht sechs Szenarien');for(const t of ["mode:'audio'","mode:'memory'","mode:'memory-chain'",'Immersion 5 · 8-Zug-Gespräch',"core.isUnlocked('immersion.transfer')",'dependencyGate:true','germanSolutionHintsAfterDay1:false'])assert(immersion.includes(t),`Immersion vermisst ${t}`);assert(!immersion.includes('data-im-choice'),'Immersion enthält Antwortbuttons');
const dialogue=read('ukrainischkurs-open-dialogue.js');assert(dialogue.includes('const VERSION=3'),'Open Dialogue ist nicht v3');assert((dialogue.match(/context:/g)||[]).length===16,'Open Dialogue enthält nicht 16 Transferfragen');assert(dialogue.includes("dayOf('Я можу · Ти можеш'"),'Open Dialogue hängt nicht an Lernobjekt Я/Ти');assert(dialogue.includes("dayOf('Ти будеш працювати?'"),'Open Dialogue hängt nicht an Zukunfts-Lernobjekt');assert(dialogue.includes('dynamicAnchors:true'),'Open Dialogue exportiert keine dynamischen Anker');assert(dialogue.includes('core.accepts(v,a)'),'Open Dialogue nutzt zentrale Bewertung nicht');
const chain=read('ukrainischkurs-conversation-chain.js');assert(chain.includes('const VERSION=3'),'Gesprächskette ist nicht v3');assert((chain.match(/hint:/g)||[]).length===14,'Gesprächsketten enthalten nicht 14 Züge');assert(chain.includes("dayOf('Він з Києва'"),'Gesprächskette hängt nicht an Herkunfts-Lernobjekt');assert(chain.includes("dayOf('п’ять квитків'"),'Gesprächskette hängt nicht an Mengen-Lernobjekt');assert(chain.includes('dynamicAnchors:true'),'Gesprächskette exportiert keine dynamischen Anker');assert(chain.includes('core.accepts(v,a)'),'Gesprächskette nutzt zentrale Bewertung nicht');
const freeRead=read('ukrainischkurs-free-reading-transfer.js');assert(freeRead.includes('const VERSION=2'),'Freier Lese-Transfer ist nicht v2');assert((freeRead.match(/text:'/g)||[]).length===3,'Freier Lese-Transfer enthält nicht drei Texte');assert(freeRead.includes("core.recordSession({skills:['reading','writing']"),'Freier Lese-Transfer schreibt keine Skill-Evidenz');

const comp=read('ukrainischkurs-comprehension-lab.js');assert(comp.includes('const VERSION=4'),'Verständnis-Labor ist nicht v4');for(const t of ['function requiredModes()','focus===\'reading\'||focus===\'listening\'','core.isIntroduced(x.uk)','adaptiveModes:true'])assert(comp.includes(t),`Verständnis-Labor vermisst ${t}`);assert(comp.includes('skills:[kind]'),'Verständnis-Labor trennt Lesen/Hören nicht');
const prod=read('ukrainischkurs-active-production.js');assert(prod.includes('const VERSION=4'),'Freie Produktion ist nicht v4');assert(!/\bmin:\s*\d+/.test(prod),'Freie Produktion enthält wieder feste min-Tagesnummern');for(const t of ['core.isIntroduced(unlockText(x))','core.reviewFocus','i%3===0',"skills:['writing','grammar']"] )assert(prod.includes(t),`Freie Produktion vermisst ${t}`);
const grammar=read('ukrainischkurs-grammar-spiral.js');assert(grammar.includes('const VERSION=4'),'Grammatik-Spirale ist nicht v4');assert(!/\bmin:\s*\d+/.test(grammar),'Grammatik-Spirale enthält wieder feste min-Tagesnummern');for(const t of ['core.isIntroduced(unlock(x))','core.reviewFocus','i%3===1',"skills:['grammar','writing']"] )assert(grammar.includes(t),`Grammatik-Spirale vermisst ${t}`);
const dict=read('ukrainischkurs-dictation.js');assert(dict.includes('const VERSION=4'),'Diktat ist nicht v4');assert(!/\bmin:\s*\d+/.test(dict),'Diktat enthält wieder feste min-Tagesnummern');for(const t of ['core.isIntroduced(x.uk)','core.reviewFocus','i%3===2',"skills:['listening','writing']",'if(!session.heard)'])assert(dict.includes(t),`Diktat vermisst ${t}`);
const adaptiveReview=read('ukrainischkurs-adaptive-review.js');assert(adaptiveReview.includes('const VERSION=1'),'Adaptiver Review ist nicht v1');for(const t of ["core.reviewFocus()==='speaking'",'core.isIntroduced(x)','slice(0,3)','session.heardBefore&&session.spoken&&session.heardAfter',"skills:['speaking']",'weight:.6','Keine automatische Akzentnote','automatic:true'])assert(adaptiveReview.includes(t),`Adaptiver Sprech-Review vermisst ${t}`);assert(!adaptiveReview.includes('data-skill-choice'),'Adaptiver Review enthält eine unerwünschte Lernweg-Auswahl');

const stories=read('ukrainischkurs-story-lab.js');assert(stories.includes('Text ausblenden & prüfen'),'Story Lab blendet Text nicht aus');
const cando=read('ukrainischkurs-a1-cando.js');assert(cando.includes('const VERSION=6'),'Can-do ist nicht v6');assert((cando.match(/\{mode:'/g)||[]).length===16,'Can-do hat nicht 16 Aufgaben');assert((cando.match(/mode:'type'/g)||[]).length===12,'Can-do hat nicht 12 freie Eingaben');assert(cando.includes("core.isUnlocked('a1.final')"),'Can-do ist nicht an Immersion-Meilenstein gebunden');
const keyboard=read('ukrainischkurs-uk-keyboard.js');assert(keyboard.includes('const VERSION=2'),'Eingabehilfe ist nicht v2');assert(!keyboard.includes('data-answer'),'Eingabehilfe enthält Lösungshinweise');
const dyn=read('ukrainischkurs-dynamic-course-ui.js');for(const t of ['function courseLength(){return Array.isArray(D)?D.length:0}','Tag ${n} · Abschluss','von ${courseLength()} Kurstagen fertig'])assert(dyn.includes(t),`Dynamische Kursanzeige vermisst ${t}`);
const profile=read('ukrainischkurs-skill-profile.js');assert(profile.includes('const VERSION=2'),'Skill-Profil ist nicht v2');for(const t of ['core.profile()','core.weakest()','core.reviewFocus()','Heutiger automatischer Review-Fokus','adaptiveReview:true'])assert(profile.includes(t),`Skill-Profil vermisst ${t}`);assert(!profile.includes('data-skill-choice'),'Skill-Profil lässt den Lernenden den Lernweg wählen');
const self=read('ukrainischkurs-selftest.js');for(const t of ['Laufzeit-Selbsttest v24','UKRAINIAN_LEARNING_CORE','core?.version>=2','core?.skills.length===5','core?.isIntroduced','core?.reviewFocus','UKRAINIAN_ADAPTIVE_REVIEW','UKRAINIAN_OPEN_DIALOGUE','UKRAINIAN_COMPREHENSION_LAB','D.length>=90'])assert(self.includes(t),`Selbsttest vermisst ${t}`);assert(self.includes('window.UKRAINIAN_COURSE_LOADER?.version===35'),'Selbsttest prüft Loader v35 nicht');assert(self.includes('Number(s.activeProduction.version)>=4'),'Selbsttest prüft Active Production v4 nicht');assert(self.includes('Number(s.grammarSpiral.version)>=4'),'Selbsttest prüft Grammar Spiral v4 nicht');assert(self.includes('Number(s.dictation.version)>=4'),'Selbsttest prüft Diktat v4 nicht');

if(errors.length){console.error(`VALIDIERUNG FEHLGESCHLAGEN (${errors.length})`);for(const e of errors)console.error('- '+e);process.exit(1)}
console.log('VALIDIERUNG OK: Syntax, Loader/Cache v35, Lernkern v2 mit dynamischer Lernobjekt-Freischaltung und review-only Skill-Fokus, fünf adaptive Skillkanäle, Review-Bänke ohne feste min-Tagesnummern, dynamische Dialog-/Gesprächsanker, adaptiver Lese-/Hörmodus, automatischer Sprechbooster, Kompetenz-Gates, ca. 90-Tage-Pfad, sicherer Offline-Fallback und Can-do v6 geprüft.');