import fs from 'node:fs';
import {test,expect} from '@playwright/test';
const budget=JSON.parse(fs.readFileSync(new URL('../performance-budget.json',import.meta.url),'utf8'));
const pct=(a,p)=>{a=[...a].sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.max(0,Math.ceil(a.length*p)-1))]||0};
const assertBudget=(name,value,limit)=>expect(value,`${name}: ${value.toFixed?.(2)??value} > budget ${limit}`).toBeLessThanOrEqual(limit);

test('V6.1 browser performance budgets',async({page})=>{
  await page.addInitScript(()=>{window.__alphaLongTasks=[];try{new PerformanceObserver(list=>window.__alphaLongTasks.push(...list.getEntries().map(e=>e.duration))).observe({entryTypes:['longtask']})}catch(_){}});
  let requests=[];page.on('request',r=>requests.push(r.url()));
  await page.goto('/alphabet-lab.html?debugLearning=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.AlphabetLab?.version===6&&window.AlphabetCoreV2?.APP_VERSION==='6.1.0');const appReadyMs=await page.evaluate(()=>performance.now());await page.waitForSelector('button');const interactiveMs=await page.evaluate(()=>performance.now());await page.waitForTimeout(250);const coldRequests=requests.length,coldJs=requests.filter(u=>/\.js(?:\?|$)/.test(u)).length;
  requests=[];await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.AlphabetLab?.version===6);await page.waitForTimeout(250);const warmRequests=requests.length,warmJs=requests.filter(u=>/\.js(?:\?|$)/.test(u)).length;
  async function sample(action,n=10){const rows=[];for(let i=0;i<n;i++){rows.push(await page.evaluate(async action=>{const t=performance.now();if(action==='home')document.querySelector('[data-nav="home"]')?.click();if(action==='alphabet')document.querySelector('[data-nav="alphabet"]')?.click();if(action==='stats')document.querySelector('[data-nav="stats"]')?.click();if(action==='question')window.AlphabetLab.startExam('quick','learning');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return performance.now()-t},action));if(action==='question')await page.evaluate(()=>window.AlphabetLab.debugHome())}return {p50:pct(rows,.5),p95:pct(rows,.95),max:Math.max(...rows)}}
  const home=await sample('home'),alphabet=await sample('alphabet');const detailRows=[];for(let i=0;i<10;i++){await page.getByRole('button',{name:'Alphabet',exact:true}).click();detailRows.push(await page.evaluate(async()=>{const t=performance.now();document.querySelector('[data-letter]')?.click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return performance.now()-t}));await page.evaluate(()=>window.AlphabetLab.debugHome())}const detail={p50:pct(detailRows,.5),p95:pct(detailRows,.95),max:Math.max(...detailRows)},stats=await sample('stats'),question=await sample('question');
  const persist=await page.evaluate(()=>{const base=window.AlphabetLab.state(),raw0=JSON.stringify(base),pad=Math.max(0,540000-raw0.length-30),raw=JSON.stringify({...base,__perfPadding:'x'.repeat(pad)}),rows=[];for(let i=0;i<80;i++){const a=performance.now();localStorage.setItem('__alpha_perf__',raw);rows.push(performance.now()-a)}localStorage.removeItem('__alpha_perf__');rows.sort((a,b)=>a-b);const p=x=>rows[Math.min(rows.length-1,Math.ceil(rows.length*x)-1)];return {bytes:new Blob([raw]).size,p50:p(.5),p95:p(.95),max:rows.at(-1)}});
  const longTaskMaxMs=await page.evaluate(()=>Math.max(0,...(window.__alphaLongTasks||[])));const report={appReadyMs,interactiveMs,coldRequests,coldJs,warmRequests,warmJs,render:{home,alphabet,detail,stats,question},persist,longTaskMaxMs};console.log('ALPHABET_BROWSER_PERF '+JSON.stringify(report));fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/v6-1-browser-performance.json',JSON.stringify(report,null,2));
  assertBudget('app ready',appReadyMs,budget.appReadyMs);assertBudget('interactive',interactiveMs,budget.interactiveMs);assertBudget('cold JS requests',coldJs,budget.criticalJsRequests);assertBudget('warm JS requests',warmJs,budget.criticalJsRequests);for(const [name,row] of Object.entries(report.render))assertBudget(`${name} render p95`,row.p95,budget.renderP95Ms);assertBudget('localStorage 540KB p95',persist.p95,budget.localStorageP95Ms);assertBudget('max long task',longTaskMaxMs,budget.longTaskMaxMs)
});
